### PR TITLE
added divehi fonts

### PR DESCRIPTION
**Pull request by naveed-ahmad**
We'll need to push font to CDN @ahmedre 

https://github.com/quran/quran.com-frontend/issues/858

### CODE REVIEW

**Comment by naveed-ahmad** [comment]
rebuid

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32954

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32876

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32882

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32884

**Pull request merged**
