### PR TITLE
Loader UI and mics issues

### PR DESCRIPTION
**Pull request by naveed-ahmad**

### CODE REVIEW

**Comment by mmahalwy** [comment]
seems like our prettier is not the same!

**Comment by naveed-ahmad** [comment]
@mmahalwy I'm on prettier 1.7.0, yours? and can we lock it to fixed version?

**Comment by mmahalwy** [comment]
@naveed-ahmad yeah we should. Mine is being weird. Yours is right

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32853

**Comment by mmahalwy** [comment]
@naveed-ahmad lmk when this is ready for review

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32879

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32932

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32965

**Comment by naveed-ahmad** [comment]
@mmahalwy ready for review and we need to lock prettier version.  Most of changes in this PR aren't mine, and PR looks like a huge things but its not. Very confused about what are real changes and what was result of prettifier :)

**Comment by mmahalwy** [comment]
@naveed-ahmad would you be able to guide me to the files changed? I can then look at those

**Comment by naveed-ahmad** [comment]
@mmahalwy closing this in favour of https://github.com/quran/quran.com-frontend/pull/963

**Pull request closed without merging**
