### PR TITLE
Audio bugs

### LINKED ISSUE #408: Changing reciters while Aayah is playing causes issues
When I play an Aayah, then I want to change reciters while the Aayah is playing, it messes up the audio player. The following happens:
1. Play a verse
2. While the verse is playing, change reciters.
3. The Aayah doesn't stop playing the previous recitation.
4. Hitting pause doesn't stop the Aayah either.
5. A bunch of stuff messes up until the previous Aayah finishes playing.

### LINKED ISSUE #733: Change reciter bug
* Play any ayah
* Change the reciter 

And you'll get hear two recitation, segments gone mad as well :)

### LINKED ISSUE #763: Audioplayer is empty when in reading mode
image

### PR DESCRIPTION
**Pull request by mmahalwy**
Fixes #763
Fixes #408
Fixes #733
Fixes https://github.com/quran/quran.com-frontend/issues/774

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32858

**Comment by naveed-ahmad** [comment]
@mmahalwy issues:
- Play first ayah http://staging.quran.com:32858/1, player don't switch to next ayah after finishing the first
- After reciting whole surah audio player start showing `loading` text, weird
- Reload the page after listing first ayah, player progress is at 100% 
- Segments aren't working in reading mode

**Comment by mmahalwy** [comment]
@naveed-ahmad can you create specific issues for some of these? So it can unblock me from fixing the immediate problems. E.g.:

`Segments aren't working in reading mode` we know this doesnt work

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by mmahalwy** [comment]
rebuild

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32818

**Pull request merged**
