### PR TITLE
Fix happypack path

### PR DESCRIPTION
**Pull request by mmahalwy**
### Title of change
_why the change and what has changed_

### Checklist

- [ ] Unit tests written
- [ ] Manually tested
- [ ] Prettier & ESLint were run
- [ ] New dependencies are included in `package-lock.json`

### Screenshot
_insert screenshot if needed_

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32783

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32784

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32785

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32786

**Comment by mmahalwy** [comment]
@naveed-ahmad all builds will fail now no?

**Comment by naveed-ahmad** [comment]
PR builds are working fine, but staging is failing. But that's another issue.

**Pull request merged**
