### PR TITLE
Route filters

### PR DESCRIPTION
**Pull request by naveed-ahmad**
Fix for https://github.com/quran/quran.com-frontend/issues/770
- /001 => /1
- /001/002 =? /1/2
- /002/info => /002/info
- /002/002:003 => /2/2-3 
- /002/002:003?translations=22 => /2/2-3?translations=22

You got the point!

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32780

**Comment by mmahalwy** [comment]
please squash! unneeded commits!

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32781

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32782

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32768

**Comment by sabeurthabti** [comment]
screen shot 2017-05-06 at 5 25 00 pm

lots of errors when click a surah from the main page.

**Comment by naveed-ahmad** [comment]
@sabeurthabti fixed

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32772

**Pull request merged**
