### PR TITLE
ui improvements for share and side bar

### PR DESCRIPTION
**Pull request by sabeurthabti**
### Title of change
UI improvements for share and side bar

share
radio

### Checklist

- [ ] Unit tests written
- [ ] Manually tested
- [ ] New dependencies were added with `yarn`
- [ ] Prettier & ESLint were run

### Screenshot
_insert screenshot if needed_

### CODE REVIEW

**Comment by sabeurthabti** [comment]
rebuild

**Comment by mmahalwy** [comment]
rebuild

**Comment by sabeurthabti** [comment]
@ahmedre jenkins :(

**Comment by mmahalwy** [comment]
rebuild

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32877

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32878

**Comment by naveed-ahmad** [comment]
There is no sidebar on staging no now, so no way to test this. Going to merge this, need to move on!

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32885

**Comment by sabeurthabti** [comment]
thank you @naveed-ahmad

**Pull request merged**
