### PR TITLE
[chore] migrating circle ci from 1.0 to 2.0

### PR DESCRIPTION
**Pull request by Dhul-Husni**
### Title of change
  - Migrate circle ci to 2.0

### Checklist
- [x] Manually tested

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32988

**Comment by mmahalwy** [comment]
@Dhul-Husni can you send an empty commit? Seems like circleci did not pick this up

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32989

**Comment by Dhul-Husni** [comment]
screen shot 2018-03-24 at 5 35 34 pm
@mmahalwy  it still thinks we are on ci 1.0
it doesn't share the same config as master
I have tested it manually both locally and on my forked branch
You could also create a branch on this repo, add this changes and test whether it builds (here)[https://support.circleci.com/hc/en-us/articles/115013849707-Can-I-use-CircleCI-1-0-and-2-0-at-the-same-time-on-a-project-]

other than that it has to be merged to master before builds start running.

**Comment by sabeurthabti** [comment]
I will look into this iA.

**Comment by sabeurthabti** [comment]
I will merge this into master and we can try it, there is no clear way to upgrade C-CI to use version 2 from the web UI.

**Comment by sabeurthabti** [comment]
for visibility, the configuration change seems to work: https://circleci.com/gh/quran/quran.com-frontend/64

@Dhul-Husni Thank you for your contribution. Would be amazing if we can do the same for https://github.com/quran/common-components

jzk

**Comment by Dhul-Husni** [comment]
@sabeurthabti  inshaAllah i will do the same

**Comment by mmahalwy** [comment]
Awesome! Thanks @sabeurthabti and @Dhul-Husni

**Pull request merged**
