### PR TITLE
Surah cleanups

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by sharabash** [comment]
i get a 'debug is not defined' error trying this out
debug is not defined

**Comment by sharabash** [comment]
debug is not defined 2
here's a screenshot with a stack trace, nice

**Comment by sharabash** [comment]
also, `const ayahRangeSize` should be in Surah/connect.js and not in Surah/index.js

**Comment by mmahalwy** [comment]
Not done not done :)

**Pull request closed without merging**
