### PR TITLE
Use new segments and surah info data

### PR DESCRIPTION
**Pull request by mmahalwy**
The backend now has new segments and surah info data.

- Incorporate the segments data from @cpfair
- Loading surah info from API as opposed to HTML files
- Removed the HTML files

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33023

**Comment by mmahalwy** [comment]
cc @cpfair

**Comment by naveed-ahmad** [comment]
Very excited about segments 🎉 🎉 🎉

**Comment by cpfair** [comment]
Could there be a link somewhere to the [repo with the raw segment data](https://github.com/cpfair/quran-align) so others can find it?

**Comment by naveed-ahmad** [comment]
@mmahalwy we can remove src/containers/Surah/description.js file as api is returning this data as well.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33024

**Pull request merged**
