### PR TITLE
added content page for tafsir

### PR DESCRIPTION
**Pull request by naveed-ahmad**
* Added tafsir icon for each ayah #639 
* Tafsir page 
* Fixed modal background color for night mode
* Refactored popup modal, controlled via common global state

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32811

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32812

**Comment by mmahalwy** [comment]
Does this fix?
 https://github.com/quran/quran.com-frontend/issues/639

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32814

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32815

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32816

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32817

**Comment by naveed-ahmad** [comment]
@mmahalwy #700 is more likely api/data related task but yeah this will fix #639 and more.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32819

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32821

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32830

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32832

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32837

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32842

**Pull request merged**
