### PR TITLE
French localization

### PR DESCRIPTION
**Pull request by ahmedre**
Add French localization, courtesy of brother Nadim Sohail, may Allah
reward him greatly!

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32773

**Comment by mmahalwy** [comment]
+1 on @naveed-ahmad

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32781

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32782

**Comment by naveed-ahmad** [comment]
@mmahalwy ready for merge

**Comment by ahmedre** [comment]
jazakAllah khairan for the fixes i missed

**Comment by mmahalwy** [comment]
Thanks for merging! :)

**Pull request merged**
