### PR TITLE
Added Indonesian Translation

### PR DESCRIPTION
**Pull request by imiro**
Added Indonesian translation as requested in issue #588 
For Indonesian contributors please do review this translation, cc: @habibr @gozali

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32775

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32776

**Comment by ahmedre** [comment]
i think you also want to add the locale to [config.js](https://github.com/quran/quran.com-frontend/blob/master/src/config.js#L22)

**Comment by mmahalwy** [comment]
@ahmedre correct! CC @imiro

**Comment by srifqi** [comment]
May I help?

**Comment by mmahalwy** [comment]
@srifqi yes please. But waiting on @imiro to update the `config.js` file.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32781

**Comment by imiro** [comment]
Right! Config.js edited

**Comment by mmahalwy** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32783

**Pull request merged**
