### PR TITLE
Moving test suite to jest

### PR DESCRIPTION
**Pull request by mmahalwy**
Because jest runs on node, importing scss files fails tests. I removed the tests for now until we remove all scss files. We are pretty close!

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32860

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32864

**Comment by sabeurthabti** [comment]
LGTMI

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32865

**Comment by sabeurthabti** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32866

**Pull request merged**
