### PR TITLE
Bumped up version of eslint

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by muhsinali** [comment]
It works!! Builds and runs. I'm getting this error in npm install though: 

>npm ERR! notarget No compatible version found: vinyl-fs@'>=0.3.0 <0.4.0'
>npm ERR! notarget Valid install targets:
>npm ERR! notarget ["0.0.1","0.0.2","0.1.0","1.0.0"]
>npm ERR! notarget 
>npm ERR! notarget This is most likely not a problem with npm itself.
>npm ERR! notarget In most cases you or one of your dependencies are requesting
>npm ERR! notarget a package version that doesn't exist.
>npm ERR! notarget 
>npm ERR! notarget It was specified as a dependency of 'gulp'
>npm ERR! notarget

**Comment by mmahalwy** [comment]
let me double check with tthat..

**Comment by mmahalwy** [comment]
@muhsinali should i merge this or have you resolved the error?

**Comment by muhsinali** [comment]
I would merge it, its running fine on my end but getting the above as a build error.

**Pull request merged**
