### PR TITLE
Better quality quran fonts

### PR DESCRIPTION
**Pull request by AbdullahObaid**
### Better quality quran fonts
I have changed quran fonts (TFF.WOFF) to another better quality version of the same font

### Checklist

- [ ] Unit tests written
- [x] Manually tested
- [ ] Prettier & ESLint were run
- [ ] New dependencies are included in `package-lock.json`

### Screenshot
explain-fonts

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32816

**Comment by naveed-ahmad** [comment]
Maybe we should create another folder `fontsv2` or something and add these fonts instead of replacing current fonts. Then change the cdn urls to `fontsv2` and use these fonts, if we font any issue later on we can simply rollback to current fonts by changing the path. Loves these new fonts but they're not tested yet. 

@AbdullahObaid thoughts?

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32817

**Comment by AbdullahObaid** [comment]
> Maybe we should create another folder `fontsv2` or something and add these fonts instead of replacing current fonts. Then change the cdn urls to `fontsv2` and use these fonts, if we found any issue later on we can simply rollback to current fonts by changing the path. Loves these new fonts but they're not tested yet.
> 
> @AbdullahObaid thoughts?
@naveed-ahmad 
The new fonts are currently used in many web apps  and they are production ready. On the other hand, most web browsers are caching webfonts so I think we should add a version number to the css file  p1.ttf?v=2

**Comment by mbana** [comment]
With the current font I cannot copy and paste. Will this fix it?

Step to reproduce:
* https://quran.com/1/1
* copy whole ayah or a word.
* attempt to paste, and I get "ﭑ ﭒ ﭓ ﭔ ﭕ".

With this site I can copy correctly:
* http://www.quran-for-all.com/translate-en_transliteration-1.html
* copy.
* paste: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ".

**Comment by naveed-ahmad** [comment]
@AbdullahObaid `p1.ttf?v=2 ` scheme is bit difficult to implement. `fonts/v1/*.ttf` and `fonts/v2/*.ttf` is lot easier.  

https://github.com/quran/quran.com-frontend/blob/e65c4fc6057732b9681d30f70e70a0c03e2e9d75/src/helpers/fontsStyle.ts#L10

We can easily switch between v1 and v2 by changing the font url
Use v1
> url('${baseUrl}/fonts/`ttf/v1`/p${pageNumber}.ttf') 

Use v2
> url('${baseUrl}/fonts/`ttf/v2`/p${pageNumber}.ttf') 

But for `p1.ttf?v=2 ` scheme, we've to rename all ttf file's name and add version number to them. 

@mbana No, unfortunately these new font won't solve this issue but we've figured out a solution for this problem. Stay tuned, next build will fix this problem inshAllah.

**Comment by AbdullahObaid** [comment]
> But for `p1.ttf?v=2 ` scheme, we've to rename all ttf file's name and add version number to them.

@naveed-ahmad no, for the ?v=XX scheme we don't need to change the file names at all. Most browsers these days will see a URL with a different query string as a different file and download a fresh copy. This is called Cache-busting.
So event both of those urls https://quran-1f14.kxcdn.com/fonts/ttf/p1.ttf AND https://quran-1f14.kxcdn.com/fonts/ttf/p1.ttf?v=2 will resolve the same file, the browser will cache them separately.

The only change we will need to do is 
` src: url('${baseUrl}/fonts/ttf/p${pageNumber}.ttf**?v=2**') `

**Comment by naveed-ahmad** [comment]
@AbdullahObaid sorry, maybe i failed explaining my point. 

- We don't want to remove current fonts, people are using em 
- So we need both of these fonts, by default show new fonts and have a way to switch back to old fonts 

 `ttf/v1/1.ttf` and `ttf/v2/1.ttf` will do the job.

**Comment by mmahalwy** [comment]
@AbdullahObaid thanks for doing this! Looks great! I agree with @naveed-ahmad, would be great to have them separated into a different directory. Technically, we need to upload them to CDN as we don't actually use the local fonts in production (only in dev, from what I remember). If it's not too much trouble, would that be possible?

cc @ahmedre

**Comment by naveed-ahmad** [comment]
Please hold on merging this PR even after moving to separate folder. We need to make sure glyph codes are same for this font.

**Comment by ahmedre** [comment]
@AbdullahObaid jazakAllah khairan these fonts do really look better - may i ask where you got them? you mentioned they are widely in use, may you point us to some apps/sites that use them?

**Comment by ahmedre** [comment]
actually, nevermind - these are the new madani fonts - in this case i recommend instead of replacing to have an option between them since some people are more comfortable reading one than another.

**Comment by mustafa0x** [comment]
I

> actually, nevermind - these are the new madani fonts - in this case i recommend instead of replacing to have an option between them since some people are more comfortable reading one than another.

In which case just pull them from http://nashr.qurancomplex.gov.sa/site/ (the fonts there are also newer than the fonts here).

**Comment by AbdullahObaid** [comment]
> @AbdullahObaid jazakAllah khairan these fonts do really look better - may i ask where you got them (i don't see a way to download these from qurancomplex's site)? you mentioned they are widely in use, may you point us to some apps/sites that use them?

They are used in http://quranapp.com

**Comment by AbdullahObaid** [comment]
Any updates?

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32841

**Comment by naveed-ahmad** [comment]
@AbdullahObaid beta.quran.com new version coming soon which has v1, v2 and couple other font options user can choose from.

**Comment by naveed-ahmad** [comment]
The latest version of v2 fonts where imported from: https://furqan.co/m-madinah-f/1/1

**Pull request closed without merging**
