### PR TITLE
Remove tilt donations link

### PR DESCRIPTION
**Pull request by mmahalwy**
### Title of change
Fixes https://github.com/quran/quran.com-frontend/issues/853

### Checklist

- [ ] Unit tests written
- [ ] Manually tested
- [ ] Prettier & ESLint were run
- [ ] New dependencies are included in `package-lock.json`

### Screenshot
_insert screenshot if needed_

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32804

**Comment by sabeurthabti** [comment]
circle-ci screen shot 2018-05-11 at 09 04 22

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32807

**Pull request merged**
