### PR TITLE
Content pages

### PR DESCRIPTION
**Pull request by naveed-ahmad**
## New content pages

- [x] tafsir

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32779

**Comment by mmahalwy** [comment]
Let's wait on the API endpoint? Or is there an endpoint for this already? Lastly, mind squashing to remove the extra commits? It will cause a disaster to commit

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32777

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32786

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32788

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32796

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32800

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32804

**Comment by naveed-ahmad** [comment]
closing in favor of https://github.com/quran/quran.com-frontend/pull/799

**Pull request closed without merging**
