### PR TITLE
Fixed an issue that was causing the wrong word to highlight

### PR DESCRIPTION
**Pull request by iMoe037**
In reference to issue #825 
The issue was the element id's were being appended with the audio position number. Each time a line component is rendered the audioPosition goes back to 1 giving the same ids on multiple lines.

To fix this instead of using audioPosition, appended the word.position on line 26. The words are now highlighted in sequential order, although the audio and highlighting are not in sync (another bug?).

I only changed the end of line 72. The pre commit hook or something else must have changed line 71 to span multiple lines.

### CODE REVIEW

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
rebuild

**Comment by ahmedre** [comment]
rebuild

**Comment by ahmedre** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32889

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32891

**Comment by naveed-ahmad** [comment]
Jazak Allah kharain for PR

**Comment by iMoe037** [comment]
No problem inshallah more coming soon!

**Comment by mmahalwy** [comment]
@iMoe037 so so awesome! Thank you

**Pull request merged**
