### PR TITLE
closes #402 re-enable auto scroll on play/next/previous

### LINKED ISSUE #402: re-enable automatic scroll with playback by default
...lots of users complaining

### PR DESCRIPTION
**Pull request by sabeurthabti**

### CODE REVIEW

**Comment by sabeurthabti** [comment]
@mmahalwy can we get this out as a hot-fix? Lots of user complaints.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32825

**Comment by ahmedre** [comment]
@sabeurthabti if you can validate that this works on the staging url above, i can merge and deploy to prod, assuming master is stable right now.

**Comment by sabeurthabti** [comment]
Yeah it's working as expected @ahmedre on staging.

**Pull request merged**
