### PR TITLE
98175224 New pagination

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by muhsinali** [comment]
When checking this out and running npm install it literally installs nothing and bombs out when I try to run ... eslint was doing the same thing ...hm

**Comment by mmahalwy** [comment]
`npm cache clean && rm -rf node_modules/ && npm install`

**Comment by mmahalwy** [comment]
But it shouldnt do that... did you restart your npm watch?

**Comment by muhsinali** [comment]
This is after clearing cache 

[0] ERROR in multi main
[0] Module not found: Error: Cannot resolve module 'eslint-loader' in /home/muhsin/proj/quran.com-frontend


[1] [piping] can't execute file: /home/muhsin/proj/quran.com-frontend/start.js
[1] [piping] error given was: Error: Cannot find module 'react-paginate'

**Comment by muhsinali** [comment]
npm ERR! peerinvalid The package eslint does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-react@2.6.4 wants eslint@>=0.8.0
npm ERR! peerinvalid Peer eslint-loader@0.14.1 wants eslint@0.21 - 0.24

**Comment by mmahalwy** [comment]
ooops! It's eslint problem. See this: https://github.com/quran/quran.com-frontend/pull/21

**Comment by muhsinali** [comment]
Looks great!! :)

**Pull request merged**
