### PR TITLE
Remove svg fonts

### LINKED ISSUE #429: Remove SVG fonts

### PR DESCRIPTION
**Pull request by ahmedre**
This patch removes svg fonts, since browsers are dropping support for
svg fonts, and, furthermore, these fonts don't actually work at the
moment. Fixes #429.

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32777

**Comment by ahmedre** [comment]
imo, there's really no strong reason to keep these - safari is the only browser that still supports it (though chrome supports it on windows, but not on other platforms):

http://caniuse.com/#feat=svg-fonts

**Comment by sabeurthabti** [comment]
agreed.

**Comment by mmahalwy** [comment]
YES!

**Comment by mmahalwy** [comment]
🔥 🔥 🔥 🔥 🔥 🔥 🔥

**Pull request merged**
