### PR TITLE
[Bug] change tooltips / fix bug

### PR DESCRIPTION
**Pull request by Dhul-Husni**
### Use a new version of tooltips
From a bug i encountered on the previous tooltips which sort it to work only when using dangerouslySetInnerHtml. other means like setting a child component instead would behave in an unpredictable manner. We sort to solve this by using a new tooltip.
### Checklist

- [ ] Unit tests written
- [x] Manually tested
- [x] Prettier & ESLint were run
- [x] New dependencies are included in `package-lock.json`

### CODE REVIEW

**Comment by sabeurthabti** [comment]
cc @ahmedre is Jenkins dead?

**Comment by ahmedre** [comment]
yes - restarted it now let's try again

**Comment by ahmedre** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33023

**Pull request merged**
