### PR TITLE
Fixed repeat audio

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by mmahalwy** [comment]
@reshadn itd be get your eyes on this

**Comment by reshadn** [comment]
@mmahalwy From what I can tell the repeat audio feature is not working. I'm assuming it's a repeat surah but from the icon it seems like a repeat ayah feature. Any additional context would be useful here. Thanks.

**Comment by mmahalwy** [comment]
Yeah it's repeat ayah not surah

**Comment by mmahalwy** [comment]
Since audio is per ayah not surah

**Comment by reshadn** [comment]
1. Would repeat ayah be indefinite? 
2. Is there a feature for repeat surah? Basically just restart ayah from # 1 after last ayah.

**Comment by mmahalwy** [comment]
1. Yes
2. No :( Because pagination

**Pull request merged**
