### PR TITLE
Fix webpack

### PR DESCRIPTION
**Pull request by mmahalwy**
TLDR;

I was really annoyed with webpack lately which caused lack of motivation to work on the project. This is aiming at making it better for me and everyone! 

Ideally, I'd like to remove bootstrap completely as it's adding a lot of build time.

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32780

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32789

**Comment by sabeurthabti** [comment]
Looks good bro, I will give it a spin tonight.

**Comment by mmahalwy** [comment]
@naveed-ahmad should fix it ^^

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32790

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32791

**Pull request merged**
