### PR TITLE
tr.js - Turkish language locale file added

### PR DESCRIPTION
**Pull request by mehmetkalayci**
Turkish language locale file added

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32776

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32777

**Comment by naveed-ahmad** [comment]
@mehmetkalayci please add locale name in config as well

https://github.com/quran/quran.com-frontend/blob/master/src/config.js#L22

**Comment by mehmetkalayci** [comment]
@naveed-ahmad Hi, I updated the https://github.com/quran/quran.com-frontend/blob/master/src/config.js#L22
I don't know very well how to use git. I hope, I didn't mistake.
jazakAllah khairan :) all of you

**Comment by naveed-ahmad** [comment]
@mehmetkalayci no problem bro, do you doing awesome job here! jazakAllah khairan for your contribution

**Pull request merged**
