### PR TITLE
Add highlight current feature

### PR DESCRIPTION
**Pull request by allyraza**
this adds highlight background for currently playing aya.

https://github.com/quran/quran.com-frontend/issues/504

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32945

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32946

**Comment by naveed-ahmad** [comment]
@allyraza shouldn't we highlight current ayat in reading mode as well?

**Comment by allyraza** [comment]
indeed that is a good feature, I never thought of that perhaps I can give it a shot next weekend.

**Comment by sabeurthabti** [comment]
@allyraza can you update your branch against master? thanks bro

**Comment by mmahalwy** [comment]
@sabeurthabti I think we can. Let me try

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32970

**Comment by mmahalwy** [comment]
@allyraza seems like in the latest build it's not working?

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32979

**Pull request merged**
