### PR TITLE
Env problems

### PR DESCRIPTION
**Pull request by mmahalwy**
For some reason, the Dockerfile envs are not getting picked up but rather .env is persisting

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32885

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32886

**Comment by mmahalwy** [comment]
@ahmedre for some reason this doesnt fix it... hrmmm

**Comment by ahmedre** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32898

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32902

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32909

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32910

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32911

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32912

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32915

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32927

**Pull request merged**
