### PR TITLE
Break down modules further

### PR DESCRIPTION
**Pull request by mmahalwy**
What the assets currently look like:

```
                        Asset     Size  Chunks                    Chunk Names
           surahinfo-chunk.js  18.5 kB      22  [emitted]         surahinfo
        images/background.jpg  17.6 kB          [emitted]
images/app-banner-android.png  92.8 kB          [emitted]
          images/index-bg.jpg  17.6 kB          [emitted]
         images/logo-lg-w.png  20.1 kB          [emitted]
           images/logo-lg.png  17.1 kB          [emitted]
           images/madinah.jpg   167 kB          [emitted]
            images/makkah.jpg   270 kB          [emitted]  [big]
    images/mockup-desktop.png   167 kB          [emitted]
 images/mockup-desktop@2x.png   564 kB          [emitted]  [big]
 images/mockup-desktop@3x.png  1.09 MB          [emitted]  [big]
    images/mockup_desktop.png   222 kB          [emitted]
 images/mockup_desktop@2x.png   743 kB          [emitted]  [big]
     images/mockup_mobile.png  67.6 kB          [emitted]
  images/mockup_mobile@2x.png   233 kB          [emitted]
     images/ornament-left.png  15.8 kB          [emitted]
    images/ornament-right.png    16 kB          [emitted]
        images/quran-logo.png  22.2 kB          [emitted]
      images/quranloading.gif  16.9 kB          [emitted]
         images/thumbnail.png   487 kB          [emitted]  [big]
     globalnav-surah-chunk.js   221 kB    0, 6  [emitted]         globalnav-surah
               surah-chunk.js   170 kB       1  [emitted]         surah
              mobile-chunk.js  27.3 kB       2  [emitted]         mobile
           donations-chunk.js  5.98 kB       3  [emitted]         donations
          contact-us-chunk.js  13.2 kB       4  [emitted]         contact-us
        smart-banner-chunk.js   172 kB       5  [emitted]         smart-banner
          global-nav-chunk.js   177 kB       6  [emitted]         global-nav
                 pdf-chunk.js   126 kB       7  [emitted]         pdf
               login-chunk.js   103 kB       8  [emitted]         login
              search-chunk.js   136 kB       9  [emitted]         search
        ayatul-kursi-chunk.js   135 kB      10  [emitted]         ayatul-kursi
             profile-chunk.js   116 kB      11  [emitted]         profile
      global-sidebar-chunk.js  78.5 kB      12  [emitted]         global-sidebar
        verse-tafsir-chunk.js  18.7 kB      13  [emitted]         verse-tafsir
        chapter-info-chunk.js  18.3 kB      14  [emitted]         chapter-info
            juz-list-chunk.js  14.5 kB      15  [emitted]         juz-list
               error-chunk.js  3.64 kB      16  [emitted]         error
               about-chunk.js  8.98 kB      17  [emitted]         about
          last-visit-chunk.js  3.57 kB      18  [emitted]         last-visit
          pdf-footer-chunk.js   2.6 kB      19  [emitted]         pdf-footer
          topoptions-chunk.js   108 kB      20  [emitted]         topoptions
         audioplayer-chunk.js   123 kB      21  [emitted]         audioplayer
       fonts/quran_common.ttf   267 kB          [emitted]  [big]
            pageview-chunk.js  13.2 kB      23  [emitted]         pageview
               share-chunk.js   105 kB      24  [emitted]         share
     verses-dropdown-chunk.js    41 kB      25  [emitted]         verses-dropdown
            settings-chunk.js  99.5 kB      26  [emitted]         settings
      repeatdropdown-chunk.js  85.6 kB      27  [emitted]         repeatdropdown
     surahs-dropdown-chunk.js  44.5 kB      28  [emitted]         surahs-dropdown
                copy-chunk.js  9.79 kB      29  [emitted]         copy
              tafsir-chunk.js  5.59 kB      30  [emitted]         tafsir
                      main.js  3.64 MB      31  [emitted]  [big]  main
          mobile-chunk.js.map    27 kB       2  [emitted]         mobile
       donations-chunk.js.map  3.71 kB       3  [emitted]         donations
      contact-us-chunk.js.map   7.7 kB       4  [emitted]         contact-us
    smart-banner-chunk.js.map   182 kB       5  [emitted]         smart-banner
      global-nav-chunk.js.map   189 kB       6  [emitted]         global-nav
           login-chunk.js.map   120 kB       8  [emitted]         login
         profile-chunk.js.map   126 kB      11  [emitted]         profile
  global-sidebar-chunk.js.map  79.6 kB      12  [emitted]         global-sidebar
 globalnav-surah-chunk.js.map   225 kB    0, 6  [emitted]         globalnav-surah
           surah-chunk.js.map   157 kB       1  [emitted]         surah
             pdf-chunk.js.map   123 kB       7  [emitted]         pdf
          search-chunk.js.map   138 kB       9  [emitted]         search
    ayatul-kursi-chunk.js.map   123 kB      10  [emitted]         ayatul-kursi
    verse-tafsir-chunk.js.map  15.3 kB      13  [emitted]         verse-tafsir
    chapter-info-chunk.js.map  14.8 kB      14  [emitted]         chapter-info
        juz-list-chunk.js.map  11.4 kB      15  [emitted]         juz-list
           error-chunk.js.map  1.99 kB      16  [emitted]         error
           about-chunk.js.map  5.92 kB      17  [emitted]         about
      last-visit-chunk.js.map  2.06 kB      18  [emitted]         last-visit
      pdf-footer-chunk.js.map  1.05 kB      19  [emitted]         pdf-footer
      topoptions-chunk.js.map   125 kB      20  [emitted]         topoptions
     audioplayer-chunk.js.map   120 kB      21  [emitted]         audioplayer
       surahinfo-chunk.js.map  20.8 kB      22  [emitted]         surahinfo
        pageview-chunk.js.map  8.86 kB      23  [emitted]         pageview
           share-chunk.js.map   125 kB      24  [emitted]         share
 verses-dropdown-chunk.js.map  41.9 kB      25  [emitted]         verses-dropdown
        settings-chunk.js.map  70.7 kB      26  [emitted]         settings
  repeatdropdown-chunk.js.map  88.1 kB      27  [emitted]         repeatdropdown
 surahs-dropdown-chunk.js.map  44.3 kB      28  [emitted]         surahs-dropdown
            copy-chunk.js.map  6.45 kB      29  [emitted]         copy
          tafsir-chunk.js.map  1.81 kB      30  [emitted]         tafsir
                  main.js.map  4.15 MB      31  [emitted]         main
```

### CODE REVIEW

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32963

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32964

**Pull request closed without merging**
