### PR TITLE
Fix staging

### PR DESCRIPTION
**Pull request by mmahalwy**
- [x] Fix search
- [x] Fixes https://github.com/quran/quran.com-frontend/issues/727
- [x] Fixes https://github.com/quran/quran.com-frontend/issues/728

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32796

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32797

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32799

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32800

**Comment by naveed-ahmad** [comment]
Couple of bugs:

- Go to http://staging.quran.com:32800/1
  - first word is pre highlighted
  - Progress bar on player is at 100% 
  - Click play on player, segments are not working. And player don't switch to next ayah
  
- Switch to second surah
  - Player keep saying loading there is break in console

**Comment by mmahalwy** [comment]
Weird, I don't get that
image

**Pull request merged**
