### PR TITLE
Text based fonts

### PR DESCRIPTION
**Pull request by naveed-ahmad**
## In this PR
- Added optimized fonts
  * Removed unused and duplicated glyph from all font files 
  *  Moved ayah number, pause mark fonts to common font file
- Regenerated fonts for each word using musharraf
- Moved userAgent to options tree

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32817

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32818

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32820

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32823

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32824

**Comment by mmahalwy** [comment]
Awesome!

**Comment by mmahalwy** [comment]
@naveed-ahmad i am good to merge this. Are you?

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32768

**Comment by naveed-ahmad** [comment]
@mmahalwy ready for merge, one issue I found and can't fix so far. Select any verse and copy the text, see arabic is joint there need to be a space between each word. Tried putting empty space &nbsp; this will fix the issue but then break the ayah numbers positions. Can you give it a try ? 

صِرَاطَالَّذِينَأَنْعَمْتَعَلَيْهِمْغَيْرِالْمَغْضُوبِعَلَيْهِمْوَلَاالضَّالِّينَ007

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32772

**Comment by mmahalwy** [comment]
Yeah, to fix it, add `&nbsp;` in between the words. It will fix it :)

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32774

**Comment by mmahalwy** [comment]
@naveed-ahmad let me know when we good!

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32779

**Comment by ysofi** [comment]
Salams,

If this only for Chrome and Opera (chromium?) what fall-back method does it use for other browsers?

The reason I'm asking is that there's some interesting things in build 32779 from above. I'm not sure if they were fixed in this PR or in another.

**Firefox 52.0.2**
1. Pause signs are showing and are not being cut. (#645)
2. The missing Alif on some ayahs like 19/26 is fixed (#645)

**Edge 38.14 and IE11(Win10, 1607)**
1. End of ayah markers are missing. Problematic for reading mode.

edge_no_marker

**Chrome 57.0.X**
1. Some ayah markers are cut off but gets fixed when
     - changing the font size on the website directly (unrelated but increasing the font size is missing, decrease is working OK.)
     - zooming in or out with browser controls
     - changing browser window width

chrome_cut_marker


**All browsers**
There is also some overlap in the diacritics. I'm not sure if this is a specific issue with ج
overlapping_diacritic _19_36

overlapping_diacritic _19_51

**Comment by mmahalwy** [comment]
@naveed-ahmad ^^

**Comment by naveed-ahmad** [comment]
@ysofi these new fonts only worked on Chrome and Opera, Firefox and Safari don't support ligature fonts on Mac. Can't test these fonts on other browsers/OS. I guess these fonts will also works with FireFox on Windows but didn't tested. We're fallbacking to old fonts for other browsers.

**Comment by naveed-ahmad** [comment]
Here is mini test for these fonts: https://ligga.herokuapp.com, if you can test on different browsers and post results in a new issue with list of browsers which render text correctly that would be very helpful and we can add more browsers. New ISSUE please :)

**Comment by ysofi** [comment]
Will create the issue shortly insha'Allah.

**Pull request merged**
