### PR TITLE
SEO/User friendly surah URL

### PR DESCRIPTION
**Pull request by sabeurthabti**
**WIP do not merge**

Salam, 

I am trying to get involved and I thought I'd tackle and minor issue I noticed. I think quran.com can benefit from include the surah name as part of the URL. For example currently `http://quran.com/2` for al-baqara, my suggestion is to have better and pretty urls like `http://quran.com/al-baqarah/2`. 

I am not an SEO guy, but I think the URL would be more identifiable when shared online, they are very user friendly and I am sure they can't harm in terms of SEO. 

This is a WIP as I explore all and change where possible. 

Let me know if you don't feel this is worth doing. 

checklist:

- [ ] use name as part of the URL or default to the id when surah name isn't available. 
- [ ] sitemap
- [ ] search and autosuggest (include ayah/range)
- [ ] quick links and footer surah links
- [ ] unit test surahUrl function
- [ ] nightwatch functional tests

### CODE REVIEW

**Comment by sabeurthabti** [comment]
I'll change and ensure this goes to the `develop` branch

**Comment by mmahalwy** [comment]
thanks @sabeurthabti

**Comment by mmahalwy** [comment]
I also think that it might be valuable to have `/al-baqarah` too. We can always add a canonical url for the actual surah name, so for google/seo reasons it's happy and likes to see the surah name rather than an id but for inside the site we can just use the id. Thoughts?

**Comment by sabeurthabti** [comment]
I will read up on canonical urls but based on my understanding, we can put the following tag(`<link rel="canonical" href="https://quran.com/al-baqarah" />`) on the each surah.

Would it be possible to retrieve a surah from the API by providing a name? else we can use  `<link rel="canonical" href="https://quran.com/al-baqarah/2" />` .

A/C:
- [ ] Add support for surah names in url
- [ ] Add add rel="canonical" to react-helmet
- [ ] maintain the usage of id

**Comment by mmahalwy** [comment]
@sabeurthabti we dont have that functionality for retrieving by name as everyone spells the names differently and we want a universal API.

**Comment by mmahalwy** [comment]
Regardless, I'd recommend having the canonical (the url google cares about) to be `/al-baqara` and no id. As far as I know, google prefers no ids.

**Comment by sabeurthabti** [comment]
Agreed on the spelling issues.

So `http://quran.com/al-baqarah` doesn't have to be a functional url? If that's case i'll make a separate PR with just `rel="canonical"` added.

**Comment by mmahalwy** [comment]
hmmm now that i think about it, it _should_ be functional... hmmm.. we are back to square one. What about this? `/2-al-baqarah` and we can then match for the id before the first dash? Hmmm, I am not sure - I really like the `/:id` but not sure if it's time we move to a text based for SEO. @sharabash @ahmedre thoughts on this?

**Comment by dashohoxha** [comment]
SEO works also with the title, meta tags etc. I don't think that url is the most important part. I am in favour of keeping the id.

**Comment by ahmedre** [comment]
i think this makes it a lot more difficult for people - i personally know that if i want verse 4 of sura 2, that i can just do /2/4 - i also think this is a lot cleaner and memorizable.

+1 on keeping ids and not introducing sura names (though if you think people will go there, you can always redirect them to the id versions).

**Comment by mmahalwy** [comment]
@ahmedre yeah, I think you have me convinced now :)

**Pull request closed without merging**
