### PR TITLE
Translated Verses Text Added

### PR DESCRIPTION
**Pull request by Skillz4Killz**
### Title of change
This PR adds the translated text for each verse. I tried to make it as close and similar to the text as it is on current production.

### Checklist

- [ ] Unit tests written
- [x] Manually tested
- [x] Prettier & ESLint were run
- [ ] New dependencies are included in `package-lock.json`

### Screenshot

**Before**

image

**After**

image

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32815

**Comment by naveed-ahmad** [comment]
@Skillz4Killz sorry I didn't get this PR, we're already showing one default translation for each ayah. Then user can select translations they want to read from settings. 

Setting are broken on staging for now, we need to fix the setting panel instead of showing this translation.

**Comment by Skillz4Killz** [comment]
Ahh if its already done thats great. I didn't see the default translation so that was why I thought it was missing. My Apologies

**Comment by naveed-ahmad** [comment]
NP, visit quran.com and you'll see the translation. Staging is broken atm :(

**Pull request closed without merging**
