### PR TITLE
Fix mismatch import / export required files / funtion

### PR DESCRIPTION
**Pull request by imadmk**
Assalamualaikum

This is pull request for issue [855](https://github.com/quran/quran.com-frontend/issues/855)

I assume that the unintended mismatch is on the imported files.

### CODE REVIEW

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by sabeurthabti** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32932

**Comment by naveed-ahmad** [comment]
@mmahalwy merging this, and few other PR. Sorry can't wait anymore for your audio player related PR :)

**Pull request merged**
