### PR TITLE
added turkish locale name in config

### PR DESCRIPTION
**Pull request by mehmetkalayci**
added turkish locale name in config line:22

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32780

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32783

**Comment by mehmetkalayci** [comment]
Hi, @mmahalwy 
Is there something I have to do about this pull request. Because When I sent a pull request before. It was accepted in a short span of time.

**Comment by mmahalwy** [comment]
rerunning it

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32800

**Comment by mehmetkalayci** [comment]
@mmahalwy @ahmedre 
Hi guys, I added turkish localization file but there are alot of english content in the website.
I'm ready to do what you need, you can just sent instruction to me via message or email.

**Comment by mmahalwy** [comment]
Thanks @mehmetkalayci ! If you can help with removing more of the english content, that'd be amazing

**Comment by mehmetkalayci** [comment]
Hi @mmahalwy ,
I believe that I can help you to translate the site, but I don't know how can I do this.
Is there any localization file? Or, Do I add data to db? What can I do, I don't know. If you guide me, I can help. Please don't hesitate to asking for help to translate turkish or anything.

**Comment by mmahalwy** [comment]
Do you mean localizing the site or translation for quran?

**Comment by mehmetkalayci** [comment]
I already added a turkish localization file. But, the site still contains english words.
If I can, I can translate that English words. Actually, I couldn't understand your question :)

**Comment by mehmetkalayci** [comment]
@mmahalwy  ??

**Comment by mmahalwy** [comment]
Yeah, please go for it! translate them over

**Pull request merged**
