### PR TITLE
Simple refactorizations.

### PR DESCRIPTION
**Pull request by UmanShahzad**
Assalamu Alaikum

This PR contains simple refactorizations, mostly recommended by ESLint. It's a basic starting point for me to delve into something a little deeper and help contribute.

It contains, as the commits note:

1. Removing of `px` or `%` qualifiers on values of 0 throughout `.scss` files. ([`@b13826e`](https://github.com/quran/quran.com-frontend/commit/b13826ee92394c75b48a66ed6cee4b6753fe0ddb))
2. Replacing of `var` with `const` when it makes sense to do so (same with `let` -> `const`). ([`@4e6ea55`](https://github.com/quran/quran.com-frontend/commit/4e6ea55fb674460c3ffc5edf7e9e91e13f1fa8ab))
3. Add/remove semicolons where it makes sense to do so. (see commit from note 3)
4. General style considerations. (see commit from note 3)

P.S. I've not done proper local testing with this yet -- having some issues with setting up a local environment right now, and a little busy with work preventing me from solving that. Just wanted to get this PR up. Hopefully CI can give us the confidence we need.

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32847

**Comment by UmanShahzad** [comment]
I think changes to `server.*.js` are causing the staging environment to break and are probably unwarranted.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32848

**Comment by UmanShahzad** [comment]
Undoing those changes fixes it.

**Pull request merged**
