### PR TITLE
Added Nafees font for Urdu and Punjabi translation

### PR DESCRIPTION
**Pull request by naveed-ahmad**
Added ability to configure fonts for translation. This PR is adding fonts for Urdu, and Punjabi language for now. But it has opened the door to add fonts for any language :)

Default font: 

New Nafees font:
2016-11-09_0407-after

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32857

**Comment by sabeurthabti** [comment]
@naveed-ahmad what are your thoughts on the font size? feels pretty small when using the new font.

**Comment by naveed-ahmad** [comment]
@sabeurthabti default fonts actually looks small to me :) any average Urdu reader can read the new 'Nafees' pretty easily. Bottom line, font size looks good to me. Urdu is my mother tongue btw.

**Comment by sabeurthabti** [comment]
LGTM

**Comment by mmahalwy** [comment]
this is awesome!! thank you thank you thank you @naveed-ahmad

**Comment by mmahalwy** [comment]
@ahmedre we may need to add these font files to the CDN please!

**Pull request merged**
