### PR TITLE
Feature/show juz Mark for verse

### PR DESCRIPTION
**Pull request by Dhul-Husni**
### Title of change
  - Feature for showing juz mark on juz start from issue #652 
  - Added internationalization onHover
### Checklist

- [x] Unit tests written
- [x] Manually tested
- [x] Prettier & ESLint were run
- [x] New dependencies are included in `package-lock.json`

### Screenshot
screen shot 2018-03-22 at 9 52 23 pm
screen shot 2018-03-22 at 11 15 28 pm

### CODE REVIEW

**Comment by Dhul-Husni** [comment]
rebuild

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32986

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32987

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32990

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32991

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32992

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32993

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32994

**Comment by sabeurthabti** [comment]
@Dhul-Husni rebase from master and we can retrigger the build. jzk

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32995

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32996

**Comment by sabeurthabti** [comment]
going to try to re-raise this pr for you again.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32998

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32999

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33000

**Comment by Dhul-Husni** [comment]
@here i am going to close this PR and create a new one. see if it builds

**Pull request closed without merging**
