### PR TITLE
Fixing Next Surah Issue

### PR DESCRIPTION
**Pull request by bahaa96**
### Title of change
Audio Player been navigating properly. A solution for #525 

### Checklist

- [ ] Unit tests written
- [ ] Manually tested
- [ ] Prettier & ESLint were run
- [ ] New dependencies are included in `package-lock.json`

### Screenshot
https://youtu.be/9JgYW1xKhzY

### CODE REVIEW

**Comment by bahaa96** [comment]
Rebuild what ?

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by naveed-ahmad** [comment]
@bahaa96 rebuild is special comment that'll trigger the build process.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32826

**Pull request closed without merging**
