### PR TITLE
Added proxy and deleted unneeded server configs

### PR DESCRIPTION
**Pull request by mmahalwy**
Going to `/api/surahs` will still work but now with a nodejs proxy rather than an API route

### CODE REVIEW

**Comment by mmahalwy** [comment]
@azizur i'd recommend taking a look at this. @ahmedre too

**Comment by ahmedre** [comment]
lgtm.

**Comment by azizur** [comment]
That was not what I meant. When I talked about proxy. I'll raise a PR with what I was talking about.

**Comment by mmahalwy** [comment]
@azizur not sure where you mentioned the proxy or anything about it - so this was not intended to be the answer for that concern.

**Pull request merged**
