### PR TITLE
Render less until client

### PR DESCRIPTION
**Pull request by mmahalwy**
Premise: `renderToString` is really slow, and even slower when there are more trees. Thus, if we get rid of components that require user interactions or do not contain links to render only on client, we can save some time! 

I am thinking I should make a util for this. Thoughts?

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32878

**Comment by mmahalwy** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32770

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32774

**Pull request merged**
