### PR TITLE
Fixes #529 PDF export

### LINKED ISSUE #529: PDF export
We get this request ALL the time. So here it goes: how do we make a PDF export of what the user is reading. For example, a user can choose to export the whole surah, or a range of ayahs, given the translations options they currently have set or we give them the option to set. It should look exactly like it looks now without the non-text components (nav, footer, audio player).

Thoughts? I am confident we can do this and have some ideas

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32859

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32860

**Comment by sabeurthabti** [comment]
any examples of url? 
`http://staging.quran.com:32860/85.pdf` doesn't work.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32867

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32868

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32869

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32870

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32871

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32872

**Comment by mmahalwy** [comment]
@sabeurthabti now i got it working!

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32873

**Comment by sabeurthabti** [comment]
@mmahalwy looks beautiful. Well done bro.

**Comment by mmahalwy** [comment]
thank you sir!

**Pull request merged**
