### PR TITLE
"initial" value does not supported in IE

### PR DESCRIPTION
**Pull request by mahboob-awan**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32824

**Comment by sabeurthabti** [comment]
might be worth merging this with the previous PR, since it a one-liner. Else +1. 

@mmahalwy what's our browser support? Maybe can we have a wiki about minimum browser support.

**Comment by mmahalwy** [comment]
@sabeurthabti that's a good question. We don't have a section or any data on that. Any thoughts on where to start? I will merge this but we can continue convo here

**Comment by mahboob-awan** [comment]
@mmahalwy @team
Suggestions:

TL;DR - Support only Evergreen browser

**Desktop**
Chrome: (Current - 1) and Current
Edge: (Current - 1) and Current
Firefox: (Current - 1) and Current
Internet Explorer: 10+
Safari: (Current - 1) and Current
Opera: Current

**Mobile**
Safari on iOS 7+

Detail: Evergreen Browsers - [link1](http://eisenbergeffect.bluespire.com/evergreen-browsers/), [link2](http://stackoverflow.com/a/19060334)

**Comment by sabeurthabti** [comment]
@mmahalwy @mahboob-awan  We will have to start with Google analytics and see what are our top browsers and start setting some rules. I'd say any browser with less than 3% should be dropped. 

We can also look at the popular browser from the top countries that visit and just make a call. I'd advise we drop support for IE 9 and thats based on what I heard a lot of major websites are doing.

**Pull request merged**
