### PR TITLE
missing segment fix

### PR DESCRIPTION
**Pull request by sabeurthabti**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32826

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32827

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32828

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32829

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32830

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32831

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32832

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32833

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32834

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32835

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32836

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32837

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32838

**Comment by sabeurthabti** [comment]
sigh, unit tests.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32842

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32843

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32844

**Comment by mmahalwy** [comment]
lgtm

**Pull request merged**
