### PR TITLE
Bump webpack and loader versions

### PR DESCRIPTION
**Pull request by mmahalwy**
### Title of change
Bump webpack and loader versions

### Checklist

- [ ] Unit tests written
- [x] Manually tested
- [x] Prettier & ESLint were run
- [x] New dependencies are included in `package-lock.json`

### Screenshot
_insert screenshot if needed_

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32982

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32983

**Comment by mmahalwy** [comment]
@sabeurthabti PTAL :)

**Comment by mmahalwy** [comment]
thanks @naveed-ahmad

**Pull request merged**
