### PR TITLE
Remove media for verses

### PR DESCRIPTION
**Pull request by mmahalwy**
In light of recent events, I think we should suspend having the videos on chapter 1.

### CODE REVIEW

**Comment by naveed-ahmad** [comment]
@mmahalwy how about just don't render the media? just remove `renderMedia` call, later on when user setting is finished, we can configure media as well.

**Comment by mmahalwy** [comment]
@naveed-ahmad thought about it but the `Verse` component is widely used so going to cut as much code as I can.

**Comment by mmahalwy** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32961

**Comment by mmahalwy** [comment]
@naveed-ahmad agreed.

**Pull request closed without merging**
