### PR TITLE
Adding PR Template

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32868

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32869

**Comment by mmahalwy** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32870

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32871

**Pull request merged**
