### PR TITLE
Sort translation languages list in alphabetical order

### LINKED ISSUE #79: Put translations in other languages in alphabetical order.

### PR DESCRIPTION
**Pull request by reshadn**
Fixes #79
screen shot 2015-10-15 at 1 42 05 am
screen shot 2015-10-15 at 1 43 12 am
screen shot 2015-10-15 at 1 43 25 am
screen shot 2015-10-15 at 1 43 37 am

### CODE REVIEW

**Comment by mmahalwy** [comment]
lgtm!

**Comment by mmahalwy** [comment]
Thanks so much!

**Comment by reshadn** [comment]
Yeah this was fun. 

@mmahalwy Sad that the CI builds failed. It says "No environment variables set". I'm assuming that's a configuration issue and not a tests failing issue?

**Comment by reshadn** [comment]
@mmahalwy After your lgtm do I merge my own PR? Any other processes to follow? Thanks.

**Comment by mmahalwy** [comment]
@reshadn it's a problem on my end. your tests are good. And yes, process is to merge your own (for those that have access at least...)

**Pull request merged**
