### PR TITLE
Return 404 when no routes found

### PR DESCRIPTION
**Pull request by mmahalwy**
### Title of change
Currently, we don't return 404 when you go to not found urls. Example of that is `http://localhost:8000/public/dist/main.js`
### Checklist

- [x] Unit tests written
- [x] Manually tested
- [x] Prettier & ESLint were run
- [x] New dependencies are included in `package-lock.json`

### Screenshot
image

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32953

**Comment by mmahalwy** [comment]
@hammady that is generated automatically by prettier on the pre-commit. :)

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32955

**Comment by mmahalwy** [comment]
hmmm.. not sure how I forgot about this... sorry guys :( I will rebase and merge

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32971

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32972

**Pull request merged**
