### PR TITLE
Issue  #472: Added tooltip prop for Ayah component in Search page

### PR DESCRIPTION
**Pull request by hassansin**
Looks like an easy fix by just adding the missing tooltip prop in `Ayah` component.

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32851

**Comment by mmahalwy** [comment]
Hmm not quite sure if that is the fix. I think the fix should be not to display a tooltip if no word translation is present, right?

**Comment by hassansin** [comment]
@mmahalwy  Actually, I don't see any tooltip at all in search page even if there is a translation available. For example, check the difference between these two pages: https://quran.com/search?q=تَبَ & http://staging.quran.com:32851/search?q=تَبَ

**Comment by hassansin** [comment]
And to address the issue of hiding tooltip if no translation is present, I think we can conditionally remove the class that shows the tooltip? For example, remove the class ` ${styles.Tooltip}` in https://github.com/quran/quran.com-frontend/blob/master/src/components/Ayah/index.js#L116  when `tooltipContent` is empty. What do you think?

**Comment by sabeurthabti** [comment]
@hassansin I can see translation on search:
screen shot 2016-09-10 at 20 49 51

**Comment by sabeurthabti** [comment]
LGTM ?
@mmahalwy thoughts? seems to fix a live bug.

**Comment by mmahalwy** [comment]
lgtm

**Comment by sabeurthabti** [comment]
@hassansin thank you for this contribution, inshallah this will be released soon.

**Comment by mmahalwy** [comment]
thanks @hassansin !

**Pull request merged**
