### PR TITLE
change default translation to The Clear Quran

### PR DESCRIPTION
**Pull request by naveed-ahmad**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32870

**Comment by mmahalwy** [comment]
What's 'The Clear Quran'?

**Comment by ahmedre** [comment]
it's Dr. Mustafa Khattab's tafseer

**Comment by mmahalwy** [comment]
@ahmedre are we merging then?

**Comment by ahmedre** [comment]
Sure, let's merge.

**Pull request merged**
