### PR TITLE
Move chapter info to container

### PR DESCRIPTION
**Pull request by mmahalwy**
### Title of change
_why the change and what has changed_

### Checklist

- [x] Unit tests written
- [x] Manually tested
- [x] Prettier & ESLint were run
- [x] New dependencies are included in `package-lock.json`

### Screenshot
_insert screenshot if needed_

### CODE REVIEW

**Comment by mmahalwy** [comment]
@sabeurthabti created this as a test and it's not running a build :( https://circleci.com/gh/quran/quran.com-frontend/tree/me--move-chapter-info-to-container2

**Comment by mmahalwy** [comment]
I cannot get circleci to work :(

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33008

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33009

**Pull request merged**
