### PR TITLE
Header on surah page

### PR DESCRIPTION
**Pull request by naveed-ahmad**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32843

**Comment by mmahalwy** [comment]
Mind if we hold on till this: https://github.com/quran/quran.com-frontend/pull/1005

**Comment by naveed-ahmad** [comment]
@mmahalwy sure :)

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32853

**Pull request closed without merging**
