### PR TITLE
Separating audio files from verses api

### PR DESCRIPTION
**Pull request by mmahalwy**
- [x] Audioplayer to use new reducer
- [x] When reciter is changed, fetch new data
- [ ] NTH: only load when audio player progresses - saving API calls

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32774

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32777

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32778

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32781

**Comment by mmahalwy** [comment]
Someone approve it :)

**Pull request merged**
