### PR TITLE
Translation url

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32801

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32816

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32822

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32776

**Comment by naveed-ahmad** [comment]
closing in favor of https://github.com/quran/quran.com-frontend/pull/797

**Pull request closed without merging**
