### PR TITLE
line-height updated.

### PR DESCRIPTION
**Pull request by arshdkhn1**
This bug can be mixture of various style. It might be present because of `font-weight` . I think using percentage for line-height is not good. % are evil in my opinion. 

This PR aims to solve [issue-548](https://github.com/quran/quran.com-frontend/issues/548).

### CODE REVIEW

**Comment by arshdkhn1** [comment]
@ahmedre  @ATouhou Can you replicate the bug even now?

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33064

**Comment by mmahalwy** [comment]
rebuild

**Comment by mmahalwy** [comment]
okay i kicked a rebuild so we can take a look at it. Inshallah this solves it!

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33065

**Comment by mmahalwy** [comment]
Hmm, that did not work. I think it has something to do with a horizontal and vertical scroll going wrong.

**Comment by mmahalwy** [comment]
Okay, I think it's something to do with the lazy load component making the scroll + rendering all weird.

**Comment by arshdkhn1** [comment]
Maybe. The repeated word isn't a new element but it is the same word. I checked it in console.

**Comment by mmahalwy** [comment]
okay that did not fix it...

**Comment by mmahalwy** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33105

**Pull request closed without merging**
