### PR TITLE
Quick links layout improved.

### PR DESCRIPTION
**Pull request by arshdkhn1**
This PR closes [issue-488](https://github.com/quran/quran.com-frontend/issues/488).

Improved Layout:
screenshot at 2016-11-14 01-12-58

Failed tests log: 
```
karma start

14 11 2016 00:45:45.611:WARN [karma]: No captured browser, open http://localhost:9876/
14 11 2016 00:45:45.625:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
14 11 2016 00:45:45.625:INFO [launcher]: Launching browser Chrome with unlimited concurrency
14 11 2016 00:45:45.758:INFO [launcher]: Starting browser Chrome
14 11 2016 00:46:17.852:INFO [Chrome 54.0.2840 (Linux 0.0.0)]: Connected on socket /#vT4Jaav5l9Mx2a4fAAAA with id 18907198
LOG: ClientRect{}
ERROR: 'Warning: Failed propType: Required prop `surah` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `onLoadAyahs` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `buildOnClient` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `isLoadedOnClient` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `isLoading` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `play` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `pause` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `next` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `previous` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `update` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `shouldScroll` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `toggleScroll` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `surah` was not specified in `RepeatButton`.'
ERROR: 'Warning: Failed propType: Required prop `shouldScroll` was not specified in `ScrollButton`.'
Chrome 54.0.2840 (Linux 0.0.0) <QuickSurahs /> Should render QuickSurahs component FAILED
	TypeError: Enzyme received a complex CSS selector ('.list-inline li') that it does not currently support
	    at selectorError (webpack:///~/enzyme/build/Utils.js:185:0 <- tests.webpack.js:8003:10)
	    at buildPredicate (webpack:///~/enzyme/build/ShallowTraversal.js:137:0 <- tests.webpack.js:25908:40)
	    at ShallowWrapper.find (webpack:///~/enzyme/build/ShallowWrapper.js:319:0 <- tests.webpack.js:26303:62)
	    at context.<anonymous> (webpack:///src/components/Home/QuickSurahs/spec.js:11:21 <- tests.webpack.js:21955:22)
Chrome 54.0.2840 (Linux 0.0.0): Executed 40 of 58 (1 FAILED) (0 secs / 0.247 secChrome 54.0.2840 (Linux 0.0.0) <QuickSurahs /> Should render QuickSurahs component with Surah Al-Kahf FAILED
	TypeError: Enzyme received a complex CSS selector ('.list-inline li') that it does not currently support
	    at selectorError (webpack:///~/enzyme/build/Utils.js:185:0 <- tests.webpack.js:8003:10)
	    at buildPredicate (webpack:///~/enzyme/build/ShallowTraversal.js:137:0 <- tests.webpack.js:25908:40)
	    at ShallowWrapper.find (webpack:///~/enzyme/build/ShallowWrapper.js:319:0 <- tests.webpack.js:26303:62)
	    at context.<anonymous> (webpack:///src/components/Home/QuickSurahs/spec.js:18:21 <- tests.webpack.js:21962:22)
Chrome 54.0.2840 (Linux 0.0.0): Executed 41 of 58 (2 FAILED) (0 secs / 0.248 secChrome 54.0.2840 (Linux 0.0.0) <SurahsList /> Should render SurahList component FAILED
	TypeError: Enzyme received a complex CSS selector ('.col-md-4 li') that it does not currently support
	    at selectorError (webpack:///~/enzyme/build/Utils.js:185:0 <- tests.webpack.js:8003:10)
	    at buildPredicate (webpack:///~/enzyme/build/ShallowTraversal.js:137:0 <- tests.webpack.js:25908:40)
	    at ShallowWrapper.find (webpack:///~/enzyme/build/ShallowWrapper.js:319:0 <- tests.webpack.js:26303:62)
	    at context.<anonymous> (webpack:///src/components/Home/SurahsList/spec.js:12:21 <- tests.webpack.js:21994:22)
Chrome 54.0.2840 (Linux 0.0.0): Executed 42 of 58 (3 FAILED) (0 secs / 0.248 secChrome 54.0.2840 (Linux 0.0.0): Executed 43 of 58 (3 FAILED) (0 secs / 0.248 secChrome 54.0.2840 (Linux 0.0.0): Executed 44 of 58 (3 FAILED) (0 secs / 0.248 secChrome 54.0.2840 (Linux 0.0.0): Executed 45 of 58 (3 FAILED) (0 secs / 0.248 secChrome 54.0.2840 (Linux 0.0.0): Executed 46 of 58 (3 FAILED) (0 secs / 0.249 secChrome 54.0.2840 (Linux 0.0.0): Executed 47 of 58 (3 FAILED) (0 secs / 0.25 secsChrome 54.0.2840 (Linux 0.0.0): Executed 48 of 58 (3 FAILED) (0 secs / 0.25 secsChrome 54.0.2840 (Linux 0.0.0): Executed 49 of 58 (3 FAILED) (0 secs / 0.25 secsChrome 54.0.2840 (Linux 0.0.0): Executed 50 of 58 (3 FAILED) (0 secs / 0.251 secERROR: 'Warning: Failed propType: Required prop `surah` was not specified in `TopOptions`.'
Chrome 54.0.2840 (Linux 0.0.0): Executed 50 of 58 (3 FAILED) (0 secs / 0.251 secERROR: 'Warning: Failed propType: Required prop `surah` was not specified in `Share`. Check the render method of `TopOptions`.'
Chrome 54.0.2840 (Linux 0.0.0): Executed 50 of 58 (3 FAILED) (0 secs / 0.251 secChrome 54.0.2840 (Linux 0.0.0): Executed 51 of 58 (3 FAILED) (0 secs / 0.253 secChrome 54.0.2840 (Linux 0.0.0): Executed 52 of 58 (3 FAILED) (0 secs / 0.254 secChrome 54.0.2840 (Linux 0.0.0): Executed 53 of 58 (3 FAILED) (0 secs / 0.255 secChrome 54.0.2840 (Linux 0.0.0): Executed 54 of 58 (3 FAILED) (0 secs / 0.255 secChrome 54.0.2840 (Linux 0.0.0): Executed 55 of 58 (3 FAILED) (0 secs / 0.256 secChrome 54.0.2840 (Linux 0.0.0): Executed 56 of 58 (3 FAILED) (0 secs / 0.257 secChrome 54.0.2840 (Linux 0.0.0): Executed 57 of 58 (3 FAILED) (0 secs / 0.257 secChrome 54.0.2840 (Linux 0.0.0): Executed 58 of 58 (3 FAILED) (0 secs / 0.258 secChrome 54.0.2840 (Linux 0.0.0): Executed 58 of 58 (3 FAILED) (0.562 secs / 0.258 secs)
14 11 2016 00:46:51.760:WARN [Chrome 54.0.2840 (Linux 0.0.0)]: Disconnected (1 tChrome 54.0.2840 (Linux 0.0.0) ERROR
  Disconnectedundefined
Chrome 54.0.2840 (Linux 0.0.0): Executed 58 of 58 (3 FAILED) (0.562 secs / 0.258 secs)
14 11 2016 00:46:52.228:ERROR [launcher]: Chrome crashed.
	
14 11 2016 00:46:52.247:INFO [launcher]: Trying to start Chrome again (1/2).
14 11 2016 00:46:54.578:INFO [Chrome 54.0.2840 (Linux 0.0.0)]: Connected on socket /#1S4g-CSCqhW1zeMwAAAB with id 18907198
LOG: ClientRect{}
ERROR: 'Warning: Failed propType: Required prop `surah` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `onLoadAyahs` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `buildOnClient` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `isLoadedOnClient` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `isLoading` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `play` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `pause` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `next` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `previous` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `update` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `shouldScroll` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `toggleScroll` was not specified in `Audioplayer`.'
ERROR: 'Warning: Failed propType: Required prop `surah` was not specified in `RepeatButton`.'
ERROR: 'Warning: Failed propType: Required prop `shouldScroll` was not specified in `ScrollButton`.'
Chrome 54.0.2840 (Linux 0.0.0) <QuickSurahs /> Should render QuickSurahs component FAILED
	TypeError: Enzyme received a complex CSS selector ('.list-inline li') that it does not currently support
	    at selectorError (webpack:///~/enzyme/build/Utils.js:185:0 <- tests.webpack.js:8003:10)
	    at buildPredicate (webpack:///~/enzyme/build/ShallowTraversal.js:137:0 <- tests.webpack.js:25908:40)
	    at ShallowWrapper.find (webpack:///~/enzyme/build/ShallowWrapper.js:319:0 <- tests.webpack.js:26303:62)
	    at context.<anonymous> (webpack:///src/components/Home/QuickSurahs/spec.js:11:21 <- tests.webpack.js:21955:22)
Chrome 54.0.2840 (Linux 0.0.0): Executed 40 of 58 (1 FAILED) (0 secs / 0.183 secChrome 54.0.2840 (Linux 0.0.0) <QuickSurahs /> Should render QuickSurahs component with Surah Al-Kahf FAILED
	TypeError: Enzyme received a complex CSS selector ('.list-inline li') that it does not currently support
	    at selectorError (webpack:///~/enzyme/build/Utils.js:185:0 <- tests.webpack.js:8003:10)
	    at buildPredicate (webpack:///~/enzyme/build/ShallowTraversal.js:137:0 <- tests.webpack.js:25908:40)
	    at ShallowWrapper.find (webpack:///~/enzyme/build/ShallowWrapper.js:319:0 <- tests.webpack.js:26303:62)
	    at context.<anonymous> (webpack:///src/components/Home/QuickSurahs/spec.js:18:21 <- tests.webpack.js:21962:22)
Chrome 54.0.2840 (Linux 0.0.0): Executed 41 of 58 (2 FAILED) (0 secs / 0.185 secChrome 54.0.2840 (Linux 0.0.0) <SurahsList /> Should render SurahList component FAILED
	TypeError: Enzyme received a complex CSS selector ('.col-md-4 li') that it does not currently support
	    at selectorError (webpack:///~/enzyme/build/Utils.js:185:0 <- tests.webpack.js:8003:10)
	    at buildPredicate (webpack:///~/enzyme/build/ShallowTraversal.js:137:0 <- tests.webpack.js:25908:40)
	    at ShallowWrapper.find (webpack:///~/enzyme/build/ShallowWrapper.js:319:0 <- tests.webpack.js:26303:62)
	    at context.<anonymous> (webpack:///src/components/Home/SurahsList/spec.js:12:21 <- tests.webpack.js:21994:22)
Chrome 54.0.2840 (Linux 0.0.0): Executed 42 of 58 (3 FAILED) (0 secs / 0.186 secChrome 54.0.2840 (Linux 0.0.0): Executed 43 of 58 (3 FAILED) (0 secs / 0.186 secChrome 54.0.2840 (Linux 0.0.0): Executed 44 of 58 (3 FAILED) (0 secs / 0.187 secChrome 54.0.2840 (Linux 0.0.0): Executed 45 of 58 (3 FAILED) (0 secs / 0.188 secChrome 54.0.2840 (Linux 0.0.0): Executed 46 of 58 (3 FAILED) (0 secs / 0.189 secChrome 54.0.2840 (Linux 0.0.0): Executed 47 of 58 (3 FAILED) (0 secs / 0.192 secChrome 54.0.2840 (Linux 0.0.0): Executed 48 of 58 (3 FAILED) (0 secs / 0.196 secChrome 54.0.2840 (Linux 0.0.0): Executed 49 of 58 (3 FAILED) (0 secs / 0.196 secChrome 54.0.2840 (Linux 0.0.0): Executed 50 of 58 (3 FAILED) (0 secs / 0.198 secERROR: 'Warning: Failed propType: Required prop `surah` was not specified in `TopOptions`.'
Chrome 54.0.2840 (Linux 0.0.0): Executed 50 of 58 (3 FAILED) (0 secs / 0.198 secERROR: 'Warning: Failed propType: Required prop `surah` was not specified in `Share`. Check the render method of `TopOptions`.'
Chrome 54.0.2840 (Linux 0.0.0): Executed 50 of 58 (3 FAILED) (0 secs / 0.198 secChrome 54.0.2840 (Linux 0.0.0): Executed 52 of 58 (3 FAILED) (0 secs / 0.203 secChrome 54.0.2840 (Linux 0.0.0): Executed 53 of 58 (3 FAILED) (0 secs / 0.204 secChrome 54.0.2840 (Linux 0.0.0): Executed 54 of 58 (3 FAILED) (0 secs / 0.205 secChrome 54.0.2840 (Linux 0.0.0): Executed 55 of 58 (3 FAILED) (0 secs / 0.209 secChrome 54.0.2840 (Linux 0.0.0): Executed 56 of 58 (3 FAILED) (0 secs / 0.211 secChrome 54.0.2840 (Linux 0.0.0): Executed 57 of 58 (3 FAILED) (0 secs / 0.211 secChrome 54.0.2840 (Linux 0.0.0): Executed 58 of 58 (3 FAILED) (0 secs / 0.211 secChrome 54.0.2840 (Linux 0.0.0): Executed 58 of 58 (3 FAILED) (0.387 secs / 0.211 secs)
```

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32878

**Comment by mmahalwy** [comment]
@arshdkhn1 thanks for this! Can you post a screenshot of how it looks on mobile?

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32879

**Comment by mmahalwy** [comment]
image

**Comment by arshdkhn1** [comment]
@mmahalwy I was thinking to change the search bar to some thing like this :
input
What do u say?

**Comment by mmahalwy** [comment]
@arshdkhn1 my fear with it is we get it, but someone who's not tech savvy will not. We have a huge range of audience so we have to be conscious about how simple and understandable everything is

**Comment by arshdkhn1** [comment]
@mmahalwy Hmm, you are right.

**Comment by arshdkhn1** [comment]
@mmahalwy Why cant I see the changes on the live website?

**Comment by mmahalwy** [comment]
@arshdkhn1 its on staging.quran.com 

We have to deploy to production for you to see them

**Pull request merged**
