### PR TITLE
Fixed audio loading

### PR DESCRIPTION
**Pull request by mmahalwy**
The audioplayer would continue to play when you visit another page or go back to the surahs list. Now, when that happens, I want to stop and destroy the audio.

### CODE REVIEW

**Comment by mmahalwy** [comment]
man :( come on tests..

**Comment by mmahalwy** [comment]
@reshadn this too

**Comment by reshadn** [comment]
@mmahalwy fixed?

**Comment by mmahalwy** [comment]
Yeah

**Pull request merged**
