### PR TITLE
Events constants and logging

### PR DESCRIPTION
**Pull request by mmahalwy**
This is a way to standardize the way we log events and name them. As noted in the file:

The goal for developers is to have them call:
```
FOOTER_EVENTS.CLICK.AUDIO;
```
and returns
```
{ NAME: 'Footer', ACTION: 'Click', LABEL: 'Audio' }
```

Better yet, calling
```
FOOTER_EVENTS.CLICK.AUDIO.PROPS;
```
will give you all the props needed for react-metrics to pass the correct data to google analytics.

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32965

**Comment by mmahalwy** [comment]
rebuild

**Comment by mmahalwy** [comment]
@naveed-ahmad I am organizing based off of GA's hierarchy. Agreed about reciters. PR to follow

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32966

**Pull request merged**
