### PR TITLE
Fixes #659 Double Click for Word Audio

### LINKED ISSUE #659: Word audio
api is now return audio file for words as well.

### PR DESCRIPTION
**Pull request by mmahalwy**
Double click does not work on mobile. We already have `onClick` for segments. Thoughts? 

I think we should remove the click for segments and just use the word audio

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32795

**Comment by naveed-ahmad** [comment]
Agreed on removing click for segments audio, word audio do the job and much better.

**Comment by cpfair** [comment]
It would be good to cancel the click event in this case - double-clicking also selects the text, which looks kind of ugly.

**Comment by mmahalwy** [comment]
okay, @naveed-ahmad and @cpfair I will switch them. Click is to play, double is to play from segment. All aboard?

**Comment by naveed-ahmad** [comment]
Double click to play from segment and continue playing, agreed with @cpfair

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32801

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32802

**Pull request merged**
