### PR TITLE
Mobile page updates

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32772

**Comment by ahmedre** [comment]
looks awesome jazakAllah khair - minor nitpicks - 
1. still says Ramadan
2. there's a 1px teal border on the top and right of the Android screenshot

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32773

**Comment by sabeurthabti** [comment]
wow mashallah thats amazing.

**Pull request merged**
