### PR TITLE
Highlight font

### PR DESCRIPTION
**Pull request by mmahalwy**
image

### CODE REVIEW

**Comment by mmahalwy** [comment]
@aam1r I'd love to get your review on this too! Need more help :)

**Comment by aam1r** [comment]
@mmahalwy sure, what's the motivation behind this?

**Comment by mmahalwy** [comment]
@aam1r when you search arabic, it should highlight the font, as seen in the picture above.

**Comment by aam1r** [comment]
@mmahalwy sweet, sounds good. Will try this out on the weekend iA.

**Comment by mmahalwy** [comment]
@aam1r its not live yet! But will be soon - this week

**Pull request merged**
