### PR TITLE
Implement sw-precache-webpack-plugin (WIP)

### PR DESCRIPTION
**Pull request by agungsb**
I've tried to implement `sw-precache-webpack-plugin` to provide Progressive Web App feature. Unfortunately, the plugin currently doesn't support `webpack-dev-server` ([explained here](https://github.com/goldhand/sw-precache-webpack-plugin/issues/17)). So it has to be run in `production` environment.

Since I can't run `npm start` (is there anyway to run as `production`?), so I couldn't check any further from my local whether the service worker is already set properly or not. But current implementation should at least let the service worker registered.

### CODE REVIEW

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by agungsb** [comment]
Hi, any follow up on this PR? It seems like there's a problem with Webpack and Karma.

**Comment by sabeurthabti** [comment]
@agungsb 

you have some linting errors, please run `npm run lint:fix` or try to fix the errors manually.

```js
/home/travis/build/quran/quran.com-frontend/src/registerServiceWorker.js
  14:67  error    'navigator' is not defined                                   no-undef
  17:7   error    'navigator' is not defined                                   no-undef
  20:11  error    Assignment to property of function parameter 'registration'  no-param-reassign
  24:21  error    'navigator' is not defined                                   no-undef
  29:19  warning  Unexpected console statement                                 no-console
  34:19  warning  Unexpected console statement                                 no-console
  41:11  warning  Unexpected console statement                                 no-console
  48:26  error    'navigator' is not defined                                   no-undef
  49:5   error    'navigator' is not defined       
```

**Comment by naveed-ahmad** [comment]
`sw-precache` is deprecated, let's use [workbox](https://developers.google.com/web/tools/workbox/) instead.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32873

**Comment by mmahalwy** [comment]
@naveed-ahmad FANTASTIC FIND! https://developers.google.com/web/tools/workbox/get-started/webpack

**Pull request closed without merging**
