### PR TITLE
Loading transition on the client

### PR DESCRIPTION
**Pull request by mmahalwy**
I have observed too many times where users click a surah and expect something to happen. And something does after all the data is resolved and a transition happens. That's not a good experience for users.

- Transitions on the client and shows loader until data is resolved
- Fixes Search Page + transitions
- Adds a new loader. The old one was great but the colors weren't even matching

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33022

**Comment by naveed-ahmad** [comment]
How about using pace ? It looks awesome! plus show actual progress of request

* http://github.hubspot.com/pace/
* https://github.com/casesandberg/react-pace

**Comment by sabeurthabti** [comment]
@mmahalwy Awesome. 

@naveed-ahmad Lets try not to add too many dependencies, they're a pain to update. We are stuck on older version of react due to boot-strap.

**Comment by mmahalwy** [comment]
@naveed-ahmad pace looks pretty awesome! We can add it to another PR but this one was specific to getting the transitions working

**Comment by mmahalwy** [comment]
Thanks @sabeurthabi!

**Pull request merged**
