### PR TITLE
#568 UI improvements

### PR DESCRIPTION
**Pull request by mmahalwy**
@umairidris this is a WIP. Check it out

Fixes https://github.com/quran/quran.com-frontend/issues/579
Fixes https://github.com/quran/quran.com-frontend/issues/578
Fixes https://github.com/quran/quran.com-frontend/issues/580
Fixes https://github.com/quran/quran.com-frontend/issues/561
Fixes https://github.com/quran/quran.com-frontend/issues/590

image

image

image

image

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33142

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33143

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33144

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33145

**Comment by umairidris** [comment]
How useful is search anyway? Having hard time thinking of a use case for myself though I'm sure others may use it. Is it worth adding to the app bar or is the one on homepage enough?

**Comment by mmahalwy** [comment]
@umairidris not sure about how useful it is when at the surah level, but search is about 1% of all our page views. Some users come specifically for search.

**Comment by umairidris** [comment]
Wow was not expecting that. If the search bar on homepage is serving the
needs of the user then I don't know if it's worth it to clutter the app bar
with a huge search bar. play music is a bit different in this than us
because searching for songs is a core action in the app.

**Comment by mmahalwy** [comment]
@umairidris right, curious what do we do with that huge space!

**Comment by sabeurthabti** [comment]
maybe we can bring reading mode, night more to fill the space. Also we can link to sister sites or put the zendesk link.

**Comment by umairidris** [comment]
I had what @sabeurthabti mentioned - one book icon for reading mode and one lightbulb for night mode and an i icon for surah info dynamically set in surah app bar. @mmahalwy had some reservations of an icon heavy design though. I think the people that would even look or care abt settings like these would eventually find it and having text description on hover can help with that.

One advantage of that design is if the window gets smaller (i.e. like in mobile), we can tuck away the settings in an overflow menu so it can scale for both mobile and desktop fairly well.

**Comment by umairidris** [comment]
I am liking the app bar switching to the surah name and having dropdown for the other surahs in your current implementation. Quite elegant.

**Comment by mmahalwy** [comment]
I am a huge huge fan of Google Photos, and this is what they do for it. 
image

image

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33159

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33160

**Comment by mmahalwy** [comment]
Wow, I cannot believe it even deployed!

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33161

**Comment by mmahalwy** [comment]
@umairidris take a look :)

**Comment by umairidris** [comment]
It seems like the PR wasn't redeployed after the last commit

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33162

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33163

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33164

**Comment by mmahalwy** [comment]
Sorry for the really really large PR :(

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33165

**Comment by umairidris** [comment]
Amazing work @mmahalwy!!

Overall the implementation looks solid. I am quite impressed you were able to make so many changes in such a short period.

I only have a few nitpicks that I can give feedback on from usability perspective (I will leave the code review to more experienced devs). Many are personal preference so feel free to take/drop as many as you and the other devs like. Also, might want to leave a lot of them off for future releases so the next release can happen soon.

- The nav drawer should have the same icon used to open it in the same location so that users can easily close it conveniently (see the mock nav bar I had in my issue)
- The app bar should probably have a bit of a different colour to stand out (maybe the same green colour as the homepage picture)
- I would bump up the font sizes of the app bar a small amount so it's more prominent against the body text
- I would prefer the home button being the first item in the nav drawer rather than being an icon in the app bar. I have not seen an app that has a home icon in the top left corner. The app bar on the home page can simply say Quran or Quran.com. 
- Having text in app bar on homepage then icons on the surah page are a bit inconsistent
- I would prefer developers and contact us in the nav bar (especially "developers" as it is an action that majority of users will not care/use). If the app bar is too empty maybe add a settings icon? I personally prefer minimalistic design so even empty bar is fine with me though others may disagree :)
- Language seems more appropriate in the settings menu
- On mobile, the icons should be put in an overflow menu and be pushed to the right edge (see: http://www.techotopia.com/images/1/14/Kindle_fire_checkable_overflow_menu.png). This is a standard and well understood action by mobile users
- See: #582. It should be implemented before this design is pushed out as this design would be painful for testing multiple reciters to find one you like. Another option that I had in mind was to have a settings page rather than modal and the font size setting can be moved there too. Then there would be a section for surah settings which would contain the reciter and font size, etc. Below there can be a small preview (maybe a small surah) that the users can see and play to test how the surah page will look. I would leave this one for a future release.
- Facebook and twitter surah icons can be moved to a "share" icon in the app bar  (which is a standard in mobile world and I am guessing anyone who would want to share to fb/twitter would understand it). Though 5 icons seems a bit much in the app bar so I would proabbly do this if the font size was moved to settings page.
- Font sizes can be changed to simpler terms like "smaller, small, normal, large, larger" if that will be more appropriate for putting it in the settings modal/page.

Bug:
- Whole homepage app bar doesn't show on mobile:
image

**Comment by mmahalwy** [comment]
@umairidris okay so a lot of the inspiration came from Google photos. As an example:
image

That should resolve these:

> - The nav drawer should have the same icon used to open it in the same location so that users can easily close it conveniently (see the mock nav bar I had in my issue)
> - The app bar should probably have a bit of a different colour to stand out (maybe the same green colour as the homepage picture)
> I would prefer the home button being the first item in the nav drawer rather than being an icon in the app bar. I have not seen an app that has a home icon in the top left corner. The app bar on the home page can simply say Quran or Quran.com.

https://storage.googleapis.com/material-design/publish/material_v_10/assets/0B6Okdz75tqQsNzVuX3hCZ3pxVmc/patterns_settings_menu.png for:
> On mobile, the icons should be put in an overflow menu and be pushed to the right edge (see: http://www.techotopia.com/images/1/14/Kindle_fire_checkable_overflow_menu.png). This is a standard and well understood action by mobile users

Agree:
> I would prefer developers and contact us in the nav bar (especially "developers" as it is an action that majority of users will not care/use). If the app bar is too empty maybe add a settings icon? I personally prefer minimalistic design so even empty bar is fine with me esp on homepage though others may disagree :)

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33166

**Comment by ahmedre** [comment]
masha'Allah, this is nice - my only feedback is that the toolbar needs some contrast from the rest of the page, especially in the Quran reading view (when not in dark mode), but also on the index.

love the new favicon btw.

**Comment by umairidris** [comment]
Was not aware that clicking on the top of nav bar closes it... can ignore the comment to add the nav bar icon to top (though it is more explicit I suppose).

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33168

**Comment by sabeurthabti** [comment]
wow mashallah beautiful

**Comment by mmahalwy** [comment]
Thank you @sabeurthabti :)

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33170

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33171

**Pull request merged**
