### PR TITLE
Just added fa: 'فارسی' to config

### PR DESCRIPTION
**Pull request by kakajan**
@naveed-ahmad ,I added fa: 'فارسی'  to available locales.
Thank you

### CODE REVIEW

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32851

**Comment by kakajan** [comment]
Wa Iyyakum Allahumma amin @naveed-ahmad, 
There is a little problem with UI for RTL languages (Arabic,Urdu and Persian). 
Input and spans direction not changing to RTL.
Is there an option to switch automatically?

**Comment by naveed-ahmad** [comment]
Wa Alakim o Salam @kakajan sorry we don't have RTL support for now.

**Pull request merged**
