### PR TITLE
Move sitemap to api

### PR DESCRIPTION
**Pull request by naveed-ahmad**

### CODE REVIEW

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32869

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32871

**Comment by ahmedre** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32890

**Pull request merged**
