### PR TITLE
#568 UI improvements

### PR DESCRIPTION
**Pull request by mmahalwy**
One of the many things from #568 :) 

- Moved all the `TopOptions` to the drawer.

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33132

**Comment by naveed-ahmad** [comment]
@mmahalwy can you add scrolling for verse dropdown ?  http://staging.quran.com:33132/2

Plus I don't like the design :)

**Comment by umairidris** [comment]
I originally did not envision things that would be commonly changed (such as verses, reading mode, etc to go into the nav drawer). I am not sure if this is the best design but would be cool if the global app bar was there and they would dynamically be added there (as icons or dropdowns)

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33134

**Comment by mmahalwy** [comment]
@naveed-ahmad sounds good. And me too, we need real design eyes to go into this. 

@umairidris I think we need to collect more data on what people change frequently. For example, recitequran.com has their options hidden and into a modal. Not sure what's best to do here but I felt like `TopOptions` is not the best.

**Comment by mmahalwy** [comment]
@umairidris i will work on global nav tomorrow inshallah

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33135

**Comment by mmahalwy** [comment]
Closing in favor of https://github.com/quran/quran.com-frontend/pull/583

**Pull request closed without merging**
