### PR TITLE
Move fonts css to be javascript

### PR DESCRIPTION
**Pull request by mmahalwy**
### Title of change
Moving the fonts setup to be in javascript and bootstrapped in the html file

### Checklist

- [ ] Unit tests written
- [x] Manually tested
- [x] New dependencies were added with `yarn`
- [x] Prettier & ESLint were run

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32886

**Comment by hammady** [comment]
Isn't `FONTS_URL` the same as `ASSET_HOST` in [this](https://github.com/hammady/quran.com-frontend/commit/2f4ae16dbe121de9b1be151c8a10f0613271f12b#comments) commit?
Should we use the latter which is more generic?
Also as for the `//` to auto-select the url scheme, is it compatible with the change in `src/config.js` in the above commit, or should we remove it in this file?

**Comment by naveed-ahmad** [comment]
Agree with @hammady we can use `ASSET_HOST` for serving all static assets( fonts, css, js ) but this isn't blocking change. We'll come back to this once cloudflare configuration are finished.

**Comment by mmahalwy** [comment]
@hammady they are not the same unfortunately. One hosts all the fonts and the other all the assets

**Pull request merged**
