### PR TITLE
97591748 Audioplayer loading icon until loaded.

### PR DESCRIPTION
**Pull request by mmahalwy**
The purpose is many people complain audio is not working but in fact it's actually just not loaded! Now left a loading icon until the audio is loaded which is conveniently really fast these days :)

### CODE REVIEW

**Comment by mmahalwy** [comment]
I will write tests soon

**Comment by muhsinali** [comment]
Looks great while loading however it doesn't want to stop loading ... it seems other branches are loading pretty promptly but this seems to get snagged somewhere, did you experience this at all?

**Comment by mmahalwy** [comment]
@muhsinali no i didnt, did you check network to see if audio is loading for you or pending?

**Comment by muhsinali** [comment]
I didn't but it looks good nothing is getting logged

**Pull request merged**
