### PR TITLE
Fix storybook with react-router

### PR DESCRIPTION
**Pull request by mmahalwy**
### Title of change
Fix storybook with react-router

### Checklist

- [x] Unit tests written
- [x] Manually tested
- [x] Prettier & ESLint were run
- [x] New dependencies are included in `package-lock.json`

### CODE REVIEW

**Comment by mmahalwy** [comment]
rebuild

**Comment by mmahalwy** [comment]
@ahmedre jenkins died?

**Comment by ahmedre** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32958

**Pull request merged**
