### PR TITLE
New reload module and cache busting

### PR DESCRIPTION
**Pull request by mmahalwy**
After build:
image

image

### CODE REVIEW

**Comment by mmahalwy** [comment]
@aam1r ^^

**Comment by mmahalwy** [comment]
it was passing..

**Comment by mmahalwy** [comment]
ill fix tests later..

**Comment by aam1r** [comment]
@mmahalwy great stuff! I'll give it a spin tomorrow or Saturday iA.

If this looks good, we should set *.js and *.css to never expire in nginx headers.

**Comment by mmahalwy** [comment]
That's @ahmedre's world (nginx) although what we should _actually_ do is put it on CDN!

**Comment by mmahalwy** [comment]
currently the js file is 600kb including vendor + our code... i want it to be smaller though :S

**Pull request merged**
