### PR TITLE
fixed Ayatul Kursi link

### PR DESCRIPTION
**Pull request by shahednasser**
### Title of change
_why the change and what has changed_
Resolving this [issue](https://github.com/quran/quran.com-frontend/issues/1076)

### Checklist

- [ ] Unit tests written
- [x] Manually tested
- [ ] Prettier & ESLint were run
- [ ] New dependencies are included in `package-lock.json`

### Screenshot
_insert screenshot if needed_

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32832

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32833

**Comment by naveed-ahmad** [comment]
@shahednasser `/ayatul-kursi` was added for seo purpose :)

**Comment by shahednasser** [comment]
I understand but the link does not work.

**Comment by naveed-ahmad** [comment]
https://staging.quran.com/ayatul-kursi

Its working, the error is in audio player :(

**Pull request closed without merging**
