### PR TITLE
Babel presets fixes

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by ahmedre** [comment]
lgtm but what i understood is you can actually remove the babel-preset-es2015-webpack dec now?

**Comment by ahmedre** [comment]
oh, you did - awesome jazakAllah khairan!

**Comment by sabeurthabti** [comment]
+1

**Comment by mmahalwy** [comment]
@ahmedre i did. See https://github.com/quran/quran.com-frontend/pull/423/files#diff-5f694022cd10cae14c85a89025b45c45R42

**Comment by ahmedre** [comment]
```
/quran/node_modules/extract-text-webpack-plugin/index.js:171
		throw new Error("Breaking change: extract now only takes a single argument. Either an options " +
		^

Error: Breaking change: extract now only takes a single argument. Either an options object *or* the loader(s).
Example: if your old code looked like this:
    ExtractTextPlugin.extract('style-loader', 'css-loader')

You would change it to:
    ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: 'css-loader' })

The available options are:
    loader: string | object | loader[]
    fallbackLoader: string | object | loader[]
    publicPath: string

    at Function.ExtractTextPlugin.extract (/quran/node_modules/extract-text-webpack-plugin/index.js:171:9)
    at Object.<anonymous> (/quran/webpack/prod.config.js:62:52)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at module.exports (/quran/node_modules/webpack/bin/convert-argv.js:93:13)
    at Object.<anonymous> (/quran/node_modules/webpack/bin/webpack.js:126:40)
```

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32771

**Pull request merged**
