### PR TITLE
Feature/sitemap

### LINKED ISSUE #381: sitemap.xml not working

### PR DESCRIPTION
**Pull request by sabeurthabti**
closes #381 

drums

### CODE REVIEW

**Comment by mmahalwy** [comment]
thank you!

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32795

**Comment by mmahalwy** [comment]
@sabeurthabti why close this? I didnt get a chance to merge it :s

**Comment by sabeurthabti** [comment]
@mmahalwy re-opened.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32796

**Comment by mmahalwy** [comment]
okay lets merge this!

**Pull request merged**
