### PR TITLE
Quick deploy changes

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32843

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32844

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32845

**Comment by naveed-ahmad** [comment]
Thanks for fixing reading mode, but please don't break normal view :)

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32847

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32848

**Pull request merged**
