### PR TITLE
Add API examples.

### PR DESCRIPTION
**Pull request by dashohoxha**
A small jQuery app that can be used to test and play with the API.
On a web server looks like this: http://dashohoxha.fs.al/quran.com-frontend/api-examples/js/

### CODE REVIEW

**Comment by sabeurthabti** [comment]
Would be nice if this was decoupled from the fontend code. Maybe can live under the api.quran.com subdomain.

**Comment by dashohoxha** [comment]
Usually it lives on the docs website (which can be on https://pages.github.com/).
In my project, it is on http://info.btranslator.org/api-examples-js/

**Comment by mmahalwy** [comment]
Agree with @sabeurthabti about decoupling.

**Comment by dashohoxha** [comment]
I agree too. You can create this project: https://github.com/quran/quran.github.io (the name of the project is **quran.github.io**), and place it there. Then it will be accessible from http://quran.github.io/api-examples/js/

This is a simple task that any beginner can do. But if you wish you can just create an empty project and give me access to it. I can give it a quick start, building something similar to: https://github.com/B-Translator/B-Translator.github.io Then every body (even a beginner) can try to improve its content and styles.

The webside http://quran.github.io/ will be like a homepage or information site for the projects related to https://github.com/quran/, and you need simple skills (HTML + CSS [+ JS +Jekyll]) to manage it, simple enough that any beginner can do.

**Pull request closed without merging**
