### PR TITLE
Fix p120 Font

### LINKED ISSUE #948: The drawing of 5:76:2 lacks 'fill'
As Salaamu Alaykum

See: https://quran.com/5/76

The issue is from the QPC's files.

Quran Android is good, but the following file also seems to have the issue: https://github.com/quran/quran.com-images/blob/master/res/fonts/QCF_P120.TTF

### PR DESCRIPTION
**Pull request by aliasaria**
This change fixes the source TTF font for p120.ttf that has an improper glyph caused by duplicate overlapping shapes.

Fixes #948

Please test because I am having issues with end of verse stop font rendering before and after this fix.

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32857

**Comment by mmahalwy** [comment]
please hold off on merging this! almost done the TS branch

**Comment by mmahalwy** [comment]
image
not working for me but this is probably cause it's not on CDN? @ahmedre ?

**Comment by aliasaria** [comment]
Any update on getting this merged? it's a small fix for a font file

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32830

**Pull request merged**
