### PR TITLE
Fix/audio player

### PR DESCRIPTION
**Pull request by AhmedShab**
### Title of change
_why the change and what has changed_

### Checklist

- [ ] Unit tests written
- [ ] Manually tested
- [ ] Prettier & ESLint were run
- [ ] New dependencies are included in `package-lock.json`

### Screenshot
_insert screenshot if needed_

### CODE REVIEW

**Comment by AhmedShab** [comment]
Salam @ahmedelgabri, I'm not quite sure why it failed the build. Is that something I have to fix at my end?

**Comment by ahmedelgabri** [comment]
> Salam @ahmedelgabri, I'm not quite sure why it failed the build. Is that something I have to fix at my end?

Salam @AhmedShab, any reason why you changed the protocol inside `package-lock.json` from `https` -> `http`? I don't think this change is needed, so revert this & wait for the tests.

**Comment by AhmedShab** [comment]
Thank you @ahmedelgabri, it was set automatically for some reason. Will fish that now 👍

**Comment by AhmedShab** [comment]
Sweet, thank you @ahmedelgabri

**Comment by AhmedShab** [comment]
There is one issue though left. We discussed it in this thread: 

https://github.com/quran/quran.com-frontend/issues/965#issuecomment-392112637

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32818

**Pull request merged**
