### PR TITLE
Fix/smart banner appid switch

### PR DESCRIPTION
**Pull request by umarsheikh13**
This is in regards to issue #604. After some testing, I realised the meta names were the other way around.

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32824

**Comment by sabeurthabti** [comment]
@umarsheikh13 nice one, tested on iOS.

Can we do something about closing the banner?

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32825

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32826

**Comment by umarsheikh13** [comment]
@sabeurthabti got the close and install links working.

**Comment by sabeurthabti** [comment]
@umarsheikh13 you're amazing mashallah. Thank you bro. LGTM!

**Pull request merged**
