### PR TITLE
Persian language for quran.com-frontend

### PR DESCRIPTION
**Pull request by kakajan**
**Assalamu alaykum**,
I just wanted to add Persian language for visitors with Persian language that may increase their interaction with Quran.com.
Jazakum Allah khair
your brother Usher (kakajan).

### CODE REVIEW

**Comment by kakajan** [comment]
Dear @naveed-ahmad I added fa: 'فارسی' to available locales in config.js file and sent another pull request.
Thank you

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32850

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32852

**Comment by naveed-ahmad** [comment]
@kakajan thank you, looks good.

We need to add missing keys for( Tafsir and Select Tafsir ) for all languages. Next PR maybe?

**Pull request merged**
