### PR TITLE
Loader overlay

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32837

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32841

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32825

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32834

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32838

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32839

**Comment by jama707** [comment]
I still see the loading overlay covering whole area and it's a bit distracting when reading. Is it possible to replace it something like http://techably.com/demo/nprogress/?

**Comment by naveed-ahmad** [comment]
@jama707 Loader is fixed here http://staging.quran.com:32853/ hopefully with next build this will goes live.

**Pull request merged**
