### PR TITLE
[fix] quran verse not showing on share

### LINKED ISSUE #932: Add verse details for social sharing.
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other

**Current behavior:**

The Social Share content is generic

**Expected / new behavior:**
We should show the shared ayah text.

**Screenshot:**

screenshot_20180121_222307

### PR DESCRIPTION
**Pull request by Dhul-Husni**
### Title of change
_why the change and what has changed_
Asalamu aleikum,
This PR fixes #932 where share was not disclosing more details about ayat.
This was due to an outdated version of react-share
React-share released version two where they changed its semantics.
### Before (v1)

```js
import { ShareButtons } from 'react-share';

const {
  FacebookShareButton,
  TwitterShareButton,
} = ShareButtons;
```

### After (v2)

```js
import {
  FacebookShareButton,
  TwitterShareButton,
} from 'react-share';
```
Some other few dependencies were also updated but still do respect `semver` which is very important.

All tests pass as expected.
Asalamu aleikum

### Checklist

- [ ] Unit tests written
- [x] Manually tested
- [x] Prettier & ESLint were run
- [x] New dependencies are included in `package-lock.json`

### Screenshot
_insert screenshot if needed_
screen shot 2018-03-09 at 10 30 06 pm

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32966

**Comment by mmahalwy** [comment]
@sabeurthabti any idea why circleci is not working here? Also, there is no link to see what the problem is

**Comment by sabeurthabti** [comment]
I will look into this tonight iA

**Comment by sabeurthabti** [comment]
rebuild

**Comment by sabeurthabti** [comment]
rebuild

**Comment by sabeurthabti** [comment]
cc @ahmedre is Jenkins okay?

**Comment by ahmedre** [comment]
jazakAllah khairan for the heads up - fixed now - let's retry

**Comment by ahmedre** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32980

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32981

**Comment by sabeurthabti** [comment]
@Dhul-Husni thanks for the tip - good to know. 
Thanks for your contribution and I hope we will see more from you. 
Jzk.

**Pull request merged**
