### PR TITLE
Add Dependency Status to Readme

### PR DESCRIPTION
**Pull request by azizur**
Add Dependency Status to Readme for easy monitor outdated dependencies.

### CODE REVIEW

**Comment by mmahalwy** [comment]
+1

**Comment by mmahalwy** [comment]
BTW pull rebase from master and your tests should pass

**Comment by azizur** [comment]
@mmahalwy I have rebased now and CI build now passes.

**Comment by mmahalwy** [comment]
Can you merge or do I need to?

**Comment by azizur** [comment]
@mmahalwy I am not a collaborators on here so I do not have access to merge things here.

**Comment by mmahalwy** [comment]
@azizur no worries. i will merge

**Pull request merged**
