### PR TITLE
update url to currently playing ayah

### PR DESCRIPTION
**Pull request by naveed-ahmad**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33197

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32777

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32780

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32801

**Comment by mmahalwy** [comment]
@naveed-ahmad can i close this for now?

**Comment by naveed-ahmad** [comment]
Sure, this was stalled anyway :)

**Pull request closed without merging**
