### PR TITLE
Optimized word fonts

### PR DESCRIPTION
**Pull request by naveed-ahmad**
### Font optimizations 

* Moved all ayah number, pause, sajdah and other glyphs in common font
* Each page has glyph only for words 

### STILL WORK IN PROGRESS 
* Glyph removed: 307342
* Glyph updated: 76650
* Total word glyph in db 77432
* Missing glyph: 782
* page 448, 495 has some issue and are not optimized yet

## UPDATE
* Fixed page 448, 495
* Glyph removed: 308364
* Glyph updated: 76904
* Missing: 528

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33130

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33131

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33136

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33137

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33138

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33139

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33140

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33141

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33155

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33158

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32803

**Comment by mmahalwy** [comment]
@naveed-ahmad is this close?

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32804

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32805

**Comment by naveed-ahmad** [comment]
@mmahalwy this is experiment PR, if new fonts works then we can merge this or close this one day. For now plz don't review or close it :)

**Comment by mmahalwy** [comment]
Cool. It's really awesome so i'd love to bring it!

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32807

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32833

**Pull request closed without merging**
