### PR TITLE
Juz tab

### PR DESCRIPTION
**Pull request by naveed-ahmad**
### Title of change
Fixed UX of juz tab 

### Checklist

- [ ] Unit tests written
- [x] Manually tested
- [x] Prettier & ESLint were run
- [ ] New dependencies are included in `package-lock.json`

### Screenshot
_insert screenshot if needed_

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32825

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32826

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32827

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32828

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32829

**Pull request merged**
