### PR TITLE
Use React-share for social icon

### PR DESCRIPTION
**Pull request by aslamhadi**
This should resolve https://github.com/quran/quran.com-frontend/issues/518

Actually I can make `Share` component as a stateless functional component if it's preferred that way. Let me know what you think

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32987

**Comment by arshdkhn1** [comment]
@aslamhadi make cursor pointer on hover.

**Comment by aslamhadi** [comment]
@arshdkhn1 done in 9ca8611 :)

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32988

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32990

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32992

**Comment by mmahalwy** [comment]
thank you!

**Pull request merged**
