### PR TITLE
Sister sites link

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32839

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32840

**Comment by sabeurthabti** [comment]
screen shot 2017-04-19 at 11 51 18 pm

**Comment by mmahalwy** [comment]
@sabeurthabti I am not a big fan of the way it looks right now :( Thinking of just having the links like we did in legacy and only on the home page.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32797

**Comment by mmahalwy** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32798

**Pull request merged**
