### PR TITLE
Fix formatting of code blocks in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ahmedelgabri**
Nothing much just fixed the formatting of code blocks.

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32810

**Comment by ahmedre** [comment]
what are the plus signs for?

**Comment by mmahalwy** [comment]
Adds a new line?

**Comment by ahmedre** [comment]
lol disregard me, i saw the + as part of the file instead of "+" as in the diff +.

**Comment by ahmedelgabri** [comment]
Yeah it was just adding a couple of new lines. A very sophisticated PR, I know :D

**Pull request merged**
