### PR TITLE
Surah page

### PR DESCRIPTION
**Pull request by naveed-ahmad**
### Verse page fixes 

- [x] Verse media 
- [x] Word audio check for pause and end character   
- [x] Translations and resource names

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32811

**Comment by mmahalwy** [comment]
Isn't `Translations and resource names` already finished?

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32812

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32813

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32814

**Pull request merged**
