### PR TITLE
Write more tests

### PR DESCRIPTION
**Pull request by mmahalwy**
### Title of change
Write more tests

### Checklist

- [x] Unit tests written
- [ ] Manually tested
- [x] New dependencies were added with `yarn`
- [x] Prettier & ESLint were run

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32903

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32905

**Comment by sabeurthabti** [comment]
I love how prettier makes tests easier to read.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32910

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32911

**Pull request merged**
