### PR TITLE
Add developer link to navbar

### PR DESCRIPTION
**Pull request by mmahalwy**
Solves #203

### CODE REVIEW

**Comment by ahmedre** [comment]
looks fine, but why make it this prominent? i think it belongs on the footer.

**Comment by mmahalwy** [comment]
Yeah it could go there too, I thought it'd be good to have a push for people helping out here by making it super prominent. What do you think @ahmedre ?

**Comment by ahmedre** [comment]
up to you, but i think until we have the repo in good state, a list of todo/starter tasks for people to pick up to get familiar with the code, etc, that it shouldn't be that prominent. but i trust your judgement.

**Comment by mmahalwy** [comment]
+1 @ahmedre going to close this

**Pull request closed without merging**
