### PR TITLE
upgrade to styled-component 3

### PR DESCRIPTION
**Pull request by sabeurthabti**
### Title of change
upgrade to styled-component 3

### Checklist

- [x] Unit tests written
- [x] Manually tested
- [x] Prettier & ESLint were run
- [x] New dependencies are included in `package-lock.json`

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32950

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32951

**Comment by mmahalwy** [comment]
@sabeurthabti how come? looks good to me!

**Comment by sabeurthabti** [comment]
it has some issues with components from our common-component modules :( 
I will look at more tonight iA

**Comment by mmahalwy** [comment]
sgtm!

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32956

**Comment by sabeurthabti** [comment]
screen shot 2018-02-07 at 23 16 06

the upgrade is causing parts of the app to break.

**Comment by sabeurthabti** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32957

**Comment by mmahalwy** [comment]
@sabeurthabti heads up, something we didn't setup is SSR and styled-components

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32967

**Comment by sabeurthabti** [comment]
Sorry for the delay with this - busy couple of weeks. I tried to setup server-side rendering, a little struggle has the document is a bit confusing. 
I'll keep trying

**Comment by mmahalwy** [comment]
@sabeurthabti can I close this?

**Pull request closed without merging**
