### PR TITLE
add Thai language support

### PR DESCRIPTION
**Pull request by ninearif**
### Title of change
add Thai language support with test included.
**Newly added:** 
-   src/locale/th.ts 

**Updated:**

- config/value.js
- src/locale/_tests_/locale.test.ts
- src/locale/index.ts

### Checklist

- [/ ] Unit tests written
- [/ ] Prettier & ESLint were run

### CODE REVIEW

**Comment by naveed-ahmad** [comment]
jazakAllah for PR, please see this.
https://github.com/quran/quran.com-frontend-v2/pull/25

Send me your email, and ill add you.

**Comment by ninearif** [comment]
> jazakAllah for PR, please see this.
> [quran/quran.com-frontend-v2#25](https://github.com/quran/quran.com-frontend-v2/pull/25)
> 
> Send me your email, and ill add you.

ninearif@hotmail.com

**Comment by naveed-ahmad** [comment]
@ninearif sent the invitation.

**Comment by ninearif** [comment]
@naveed-ahmad Completed in translation to Thai, what should I do next?

**Comment by naveed-ahmad** [comment]
@ninearif jazakAllah kharain for contributing brother, you can test Thai language on https://beta.quran.com/ now :) 

This will be love on production site soon.

**Comment by ninearif** [comment]
@naveed-ahmad I think I need to improve the translation, but I have a problem I can't access to the project on  https://translation.io

**Comment by naveed-ahmad** [comment]
@ninearif please try again.

**Comment by ninearif** [comment]
> @ninearif please try again.

Thanks.

**Pull request closed without merging**
