### PR TITLE
Merge pull request #1 from quran/master

### PR DESCRIPTION
**Pull request by AhmedShab**
Merge from master branch

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32853

**Comment by AhmedShab** [comment]
Sorry, my bad. I'm trying to figure out how I can get everything from master to my own forked branch

**Comment by sabeurthabti** [comment]
@AhmedShab have a read of : https://github.com/quran/quran.com-frontend/blob/master/CONTRIBUTING.md

**Comment by AhmedShab** [comment]
Thanks man

**Pull request closed without merging**
