### PR TITLE
Added favicons, opensearch, and manifest files for chrome

### PR DESCRIPTION
**Pull request by naveed-ahmad**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32977

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32978

**Comment by mmahalwy** [comment]
hmm why can't i merge this...

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32980

**Comment by naveed-ahmad** [comment]
Merging with banner PR

**Comment by naveed-ahmad** [comment]
@mmahalwy merged this with https://github.com/quran/quran.com-frontend/pull/508 as I need manifest files to test the native banner.

**Pull request closed without merging**
