### PR TITLE
Quran frontend v2

### PR DESCRIPTION
**Pull request by mmahalwy**
### Title of change
Quran frontend v2

- [x] Moving to Typescript
- [x] Removing the connect files and using async bootstrap
- [x] Creating containers down the tree for Verses, Words, Audioplayer
- [x] Containing all the translation ids to one file
- [x] API requests handled by `redux-pack` instead of `clientMiddleware`
- [x] Breaking down and separating reducers doing more than they should
- [x] Removing `ApiClient`
- [x] Routes handled by `react-router` on server and client
- [x] Figuring out what to do with `normalizr`
- [x] Navbars handled by `react-router` on server and client
- [x] Chapter navbar is a container and dispatches actions
- [x] Audioplayer is a container not dispatching all changes to redux
- [x] Write tests
- [ ] Write stories
 

### Checklist

- [x] Unit tests written
- [x] Manually tested
- [x] Prettier & ESLint were run
- [x] New dependencies are included in `package-lock.json`

### Screenshot
_insert screenshot if needed_

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32854

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32855

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by mmahalwy** [comment]
@naveed-ahmad it builds!!! WOOWW!

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32859

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32861

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32862

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32863

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32864

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32865

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32866

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32867

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32868

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32869

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32870

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32871

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32872

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32873

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32874

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32875

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32876

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32877

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32878

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32879

**Comment by naveed-ahmad** [comment]
Been waiting for this for so long. Thanks <3

**Comment by mmahalwy** [comment]
@naveed-ahmad thank you! Finally finished! Although there are a few things I forgot, but created an issue for it

**Pull request merged**
