### PR TITLE
increase line height to make it more readable on mobile

### PR DESCRIPTION
**Pull request by redhae**

### CODE REVIEW

**Comment by mmahalwy** [comment]
Looks good to me! 

Thanks @redhae :) Merge it!

**Comment by redhae** [comment]
image

**Comment by redhae** [comment]
@mmahalwy how do we merge it? sorry i'm not familiar with the process (prob need an admin to merge it?)

**Comment by muhsinali** [comment]
@redhae You should see a box under the last comment stating "Merge pull request" 

merge

If you don't see that post back and we'll take care of it insha'Allah thanks!

**Comment by redhae** [comment]
ah, i'm not seeing that:

image

**Comment by muhsinali** [comment]
@redhae I merged it for you, if you plan on making more contributions I recommend getting in touch with @mmahalwy Thanks!

**Comment by redhae** [comment]
@muhsinali thanks!

**Pull request merged**
