### PR TITLE
Remove missing contents

### PR DESCRIPTION
**Pull request by nurazhar**

### CODE REVIEW

**Comment by mmahalwy** [comment]
rebuild

**Comment by mmahalwy** [comment]
Thank you!

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33169

**Comment by mmahalwy** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33172

**Comment by mmahalwy** [comment]
@ahmedre why is this broken. it's a readme change :S

**Comment by ahmedre** [comment]
rebuild

**Comment by ahmedre** [comment]
the error yesterday was in calling github's api. today, it seems like the container wasn't properly removed before deploying the new one - i've seen this happen before and am uncertain as to why at the moment, will keep an eye on it though.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33173

**Pull request merged**
