### PR TITLE
WIP: V3 API

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32810

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32811

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32816

**Comment by mmahalwy** [comment]
@sabeurthabti thanks for the review! Still WIP though... I haven't finished the Surah page, etc.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32827

**Comment by mmahalwy** [comment]
@naveed-ahmad going to merge this so i can unblock other issues

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32792

**Pull request merged**
