### PR TITLE
Add .sq locale

### PR DESCRIPTION
**Pull request by korabh**
Add Albanian translation file

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32919

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32920

**Comment by naveed-ahmad** [comment]
JAK for your contributions @korabh 

Can you please add a locale for these two messages as well? We actually need to localize these two strings for all languages :)

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32923

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32926

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32942

**Pull request merged**
