### PR TITLE
Docker swarm

### PR DESCRIPTION
**Pull request by mmahalwy**
### Title of change
_why the change and what has changed_

### Checklist

- [ ] Unit tests written
- [ ] Manually tested
- [ ] Prettier & ESLint were run
- [ ] New dependencies are included in `package-lock.json`

### Screenshot
_insert screenshot if needed_

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32925

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32926

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32927

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32928

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32929

**Comment by hammady** [comment]
Can this be merged?

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32938

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32941

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32947

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32948

**Comment by UmanShahzad** [comment]
@mmahalwy Is this one to throw out? Was the migration to docker swarm successful, etc.?

**Pull request closed without merging**
