### PR TITLE
(WIP) Integration work with quran-components

### PR DESCRIPTION
**Pull request by sabeurthabti**
This is phrase one of integrating [quran-components](https://github.com/quran/common-components), demo page can be found [here](https://quran.github.io/common-components).

- [x] Jumbotron
- [x] SurahTitle
- [ ] Loader

Note:

All the SVG's will be housed in: https://github.com/quran/common-components/tree/master/utils/surahTitleSvg

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32826

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32827

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32830

**Comment by mmahalwy** [comment]
🔥 🔥 🔥 🔥 🔥

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32832

**Comment by mmahalwy** [comment]
@sabeurthabti loader done? Good to review?

**Comment by sabeurthabti** [comment]
Please review 🙏

There is a bug on staging, we should fix that before merging more stuff in.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32776

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32778

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32780

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32783

**Comment by sabeurthabti** [comment]
Thanks for merging this in guys <3 Sorry got so busy this week :(

**Pull request merged**
