### PR TITLE
Some cleanups on components

### PR DESCRIPTION
**Pull request by mmahalwy**
### Title of change
Few cleanups

### Checklist

- [ ] Unit tests written
- [ ] Manually tested
- [x] New dependencies were added with `yarn`
- [x] Prettier & ESLint were run

### Screenshot
_insert screenshot if needed_

### CODE REVIEW

**Comment by mmahalwy** [comment]
rebuild

**Comment by mmahalwy** [comment]
rebuild

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by mmahalwy** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32893

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32896

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32904

**Pull request merged**
