### PR TITLE
Remove more SCSS and adding storybook for better component developing

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by mmahalwy** [comment]
rebuild

**Comment by mmahalwy** [comment]
bump @sabeurthabti @naveed-ahmad

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32857

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32859

**Comment by mmahalwy** [comment]
Went through the site and all looks the same. Going to merge this. If we catch anything in staging, will put a PR.

**Pull request merged**
