### PR TITLE
remove travis and use circle

### PR DESCRIPTION
**Pull request by sabeurthabti**
### Align build tools across projects

We use circle-ci on the common-components project. Let's keep Travis, get the project setup on Circle and then we can delete the Travis fie.

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32935

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32936

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32937

**Comment by sabeurthabti** [comment]
I am going to merge this and get circle to build. @ahmedre @mmahalwy

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32939

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32940

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32942

**Pull request merged**
