### PR TITLE
Fixes #544 local for google index

### LINKED ISSUE #544: local specific meta tags
https://github.com/quran/quran.com-frontend/pull/523 will add localization now its time to update meta tags. 

* dynamically set `og:locale` value according to current local
* Add tags alternate tags for available locals
```html 
<link rel='alternate' href="https://quran.com/...?local=?local" hreflang="LOCAL"> 
``` 
* make sure canonical meta is without local param

### PR DESCRIPTION
**Pull request by mmahalwy**
Skipping `og:locale` for now.

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32874

**Comment by mmahalwy** [comment]
rebuild

**Comment by mmahalwy** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32768

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32771

**Pull request merged**
