### PR TITLE
Webpack 2

### PR DESCRIPTION
**Pull request by mmahalwy**
Fixes https://github.com/quran/quran.com-frontend/issues/575

### CODE REVIEW

**Comment by mmahalwy** [comment]
come on jenkins!

**Comment by mmahalwy** [comment]
it will finish tomorrow @ahmedre

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33179

**Comment by mmahalwy** [comment]
woohoo!

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33180

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:33192

**Comment by mmahalwy** [comment]
Going to merge this folks, nothing special done here other than removing some react-bootstrap and updating to webpack-2 + it's new configs.

**Pull request merged**
