### PR TITLE
Upgrading to react-router 4

### PR DESCRIPTION
**Pull request by mmahalwy**
### Title of change
Upgrading to react-router 4

### Checklist

- [ ] Unit tests written
- [x] Manually tested
- [x] New dependencies were added with `yarn`
- [x] Prettier & ESLint were run

### Screenshot
_insert screenshot if needed_

### CODE REVIEW

**Comment by mmahalwy** [comment]
@sabeurthabti wanted to get your thoughts on how to handle the server-side stuff and code splitting. So far, this is a pain

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32874

**Comment by sabeurthabti** [comment]
@mmahalwy I will be looking into this tomorrow iA

**Comment by mmahalwy** [comment]
@sabeurthabti okay, this is working. I don't want to make this PR any larger and feel like a follow up PR can follow to polish. I think this is a good place to stop

**Comment by sabeurthabti** [comment]
Tbh I have not done much server-rendering recently, so I wouldn't have had much input. 
Glad it is working. Let's get this merged in .

**Comment by mmahalwy** [comment]
rebuild

**Comment by mmahalwy** [comment]
@ahmedre I think jenkins died again :I

**Comment by ahmedre** [comment]
rebuild

**Comment by ahmedre** [comment]
thanks for the heads up - should be good now

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32875

**Pull request merged**
