### PR TITLE
Update id.js

### PR DESCRIPTION
**Pull request by habibr**
Adding and editing indonesian translation.

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32788

**Comment by habibr** [comment]
Why changing language does not work at the staging site? http://staging.quran.com:32788
Or I missed something?

**Comment by ahmedre** [comment]
@naveed-ahmad - any ideas?

**Comment by naveed-ahmad** [comment]
@ahmedre there was JS break, fixed here: https://github.com/quran/quran.com-frontend/pull/622

**Comment by ahmedre** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32794

**Comment by ahmedre** [comment]
@naveed-ahmad i see it in drop down but changing languages don't work at the moment - maybe because of flux of api v2/v3 - i'll go ahead and accept and merge this.

jazakAllah khairan @habibr

**Comment by ahmedre** [comment]
talked to Naveed, looks like it's because we didn't rebase onto his patch, which means insha'Allah staging.quran.com should reflect your changes once it's deployed sometime soon.

**Pull request merged**
